### PR TITLE
Fix #818

### LINKED ISSUE #818: Error in log from missing metadata.json
Briefcase on the CLI reports an error: 

```
Unexpected error in Briefcase. Please review briefcase.log for more information. For help, post to https://forum.opendatakit.org/c/support
```

The log has
```
java.io.UncheckedIOException: java.nio.file.NoSuchFileException: uga/ODK Briefcase Storage/uga/ODK Briefcase Storage/forms/IOMHHSurveyer_V6/metadata.json
	at org.opendatakit.briefcase.reused.UncheckedFiles.write(UncheckedFiles.java:80)
	at org.opendatakit.briefcase.reused.UncheckedFiles.write(UncheckedFiles.java:73)
	at org.opendatakit.briefcase.model.form.FileSystemFormMetadataAdapter.serialize(FileSystemFormMetadataAdapter.java:123)
	at org.opendatakit.briefcase.model.form.FileSystemFormMetadataAdapter.persist(FileSystemFormMetadataAdapter.java:96)
	at java.base/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:441)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1621)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.opendatakit.briefcase.model.form.FileSystemFormMetadataAdapter.syncWithFilesAt(FileSystemFormMetadataAdapter.java:75)
	at org.opendatakit.briefcase.model.form.FileSystemFormMetadataAdapter.at(FileSystemFormMetadataAdapter.java:33)
	at org.opendatakit.briefcase.operations.PullFormFromAggregate.pullFormFromAggregate(PullFormFromAggregate.java:90)
	at org.opendatakit.briefcase.operations.PullFormFromAggregate.lambda$static$0(PullFormFromAggregate.java:69)
	at org.opendatakit.common.cli.Cli.lambda$run$4(Cli.java:130)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.opendatakit.common.cli.Cli.run(Cli.java:127)
	at org.opendatakit.briefcase.Launcher.main(Launcher.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.nio.file.NoSuchFileException: uga/ODK Briefcase Storage/uga/ODK Briefcase Storage/forms/IOMHHSurveyer_V6/metadata.json
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:223)
	at java.base/java.nio.file.Files.write(Files.java:3488)
	at org.opendatakit.briefcase.reused.UncheckedFiles.write(UncheckedFiles.java:78)
	... 23 common frames omitted
```

### PR DESCRIPTION
**Pull request by cletusajibade**
Closes #818

#### What has been done to verify that this works as intended?
Pulling from Aggregate server through CLI

#### Why is this the best possible solution? Were any other approaches considered?
This solution checks to make sure the metadata directory can be resolved. No other approach considered.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Change does not affect users.

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
No

### CODE REVIEW

**Comment by cletusajibade** [comment]
> Hi, @cletusajibade!
> 
> I don't think this method should throw any exception. See other similar methods like the one in `FormStatus`. Their goal is just to build `Path` objects for us without checking whether they exist or not.
> 
> Also, I'm not convinced that the proper way to respond to this would be to throw an error, since the involved paths can be missing the first time we want to create them.
> 
> I think that a better approach would be to ensure that the parent directory exists by creating it before trying to write the metadata file. Could you consider this approach, please?

Ok, I will try this approach.

**Comment by cletusajibade** [comment]
Hi, @ggalmazor , I sent a PR again yesterday.

**Comment by ggalmazor** [comment]
I'm not sure if you want to continue with this PR or #846. Once you tell me what you want to do, I'll review

File: src/org/opendatakit/briefcase/model/form/FileSystemFormMetadataAdapter.java [hunk 1]
```diff
@@ -132,12 +133,23 @@ private static FormMetadata deserialize(Path storageRoot, Path metadataFile) {
 
   private static Path serialize(FormMetadata metaData) {
     try {
-      return write(
-          getMetadataFile(metaData),
-          MAPPER.writerWithDefaultPrettyPrinter().writeValueAsString(metaData.asJson(MAPPER)),
-          CREATE, TRUNCATE_EXISTING
-      );
-    } catch (JsonProcessingException e) {
+      Path formDir = metaData.getFormDir();
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/model/form/FileSystemFormMetadataAdapter.java]: This method has duplicated code that could be simplified by calling `UncheckedFiles.createDirectories()` unconditionally before the `write` call.

Comment (cletusajibade) [reply src/org/opendatakit/briefcase/model/form/FileSystemFormMetadataAdapter.java]: That is correct. I will make the changes right now.

File: src/org/opendatakit/briefcase/model/form/FileSystemFormMetadataAdapter.java [hunk 2]
```diff
@@ -130,21 +131,12 @@ private static FormMetadata deserialize(Path storageRoot, Path metadataFile) {
...
-            CREATE, TRUNCATE_EXISTING
-        );
-      }
-
+      UncheckedFiles.createDirectories(formDir);
+      return write(
+          getMetadataFile(metaData),
+          MAPPER.writerWithDefaultPrettyPrinter().writeValueAsString(metaData.asJson(MAPPER)),
+          CREATE, TRUNCATE_EXISTING
+      );
```
Comment (cletusajibade) [inline src/org/opendatakit/briefcase/model/form/FileSystemFormMetadataAdapter.java]: @ggalmazor here are the changes.

**Comment by ggalmazor** [comment]
(Future reminder to **squash merge this PR**)

**Comment by kkrawczyk123** [comment]
I wasn't able to reproduce an issue in multiple tries so I guess we have success here!
Verified on Ubuntu, MacOS and Windows.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
