### PR TITLE
Fixed #140: Recorded instance check performance degrades proportional…

### LINKED ISSUE #140: Recorded instance check performance degrades proportionally with total instances
Seen while working on a prototype for #138, based on 1.6.10.

With the improvement in download performance of the #138 prototype, I noticed instance fetch performance became unexpectedly poor for forms with larger number of submissions. Also, resuming a form download after a previous batch of fetches was slow even when no instance downloads occur.

The reason for this behavior is the implementation of the form instance tracking. Specifically, `DatabaseUtils.hasRecordedInstance(...)` gets proportionally slower with the number of form instances tracked for the form. Since this method is called for each form instance, the linear increase in execution time of each call results in an exponential increase in the time needed to fetch all instances. The problem is *very noticeable* once a form's `recorded_instance` table approaches the 50,000 record range.

The acute problem is the sql query `SELECT directory FROM recorded_instance WHERE instanceId = ?` requires a full table scan. The solution: index the `instanceId` column. However, smallsql does not appear to support indexes.

To confirm the fix: I swapped instance tracking to use hsql with an indexed `instanceId` column. Instance check performance improved considerably even for small numbers of instances, and the performance level did not degrade proportionally with the number of tracked instances.

### PR DESCRIPTION
**Pull request by batkinson**
Significantly improves performance of instance tracking by migrating briefcase form instance db to use hsql. Necessary due to the lack of an indexing feature in smallsql.

### CODE REVIEW

**Comment by lognaturel** [comment]
This definitely seems like a really great idea! The big question for me is how to minimize the impact on existing users. If I'm understanding correctly, what would happen with the db change as written is that no downloaded submissions would be recognized after the Briefcase update because although the files would still exist, the DB records would no longer be recognized. Users would continue to have a stale `info.db` folder.

I think this might be pretty confusing and it might be better to have some kind of migration to make the change a little more seamless. What do you think, @yanokwa?

**Comment by yanokwa** [comment]
Agreed with @lognaturel that it would be good to have some migration story. 

I'm thrilled with the removal of SmallSQL since it hasn't been updated since 2011, but I'm curious why HSQLDB was used instead of SQLite?

**Comment by batkinson** [comment]
Too much to say in response, but of the PRs for #138, #140 and #141 this is the one I would knew would be most likely to be rejected. However, I submitted it because it's a working fix for a debilitating scale problem users have *today*.

In terms of impact, you may be over-stating it, especially compared with the problems the issue causes. I suspect users that have large data sets just abandoned the idea of using briefcase once they tried it in practice. We almost did.

@yanokwa, the hsql choice was fairly arbitrary. HSQL is popular enough, as is H2, and it's more powerful than sqlite. However, that misses the point. *Any* database that supports indexing can be used to fix the problem.

If you want, I can resubmit with sqlite, but it's unlikely I have the cycles to build a complete migration solution (also, I am not convinced it's overly important given how fast re-verification once this is fixed). However, we can't use the existing tool as-is so I figured I would offer it up.

**Comment by batkinson** [comment]
@yanokwa, not sure I understand the motivation for using sqlite here. The purpose is fast lookup of the instance directory based on instanceId, which the previous implementation fails at because it doesn't use indexes. If the popularity of the db tech matters, I guess I am missing the point. Smallsql wasn't exactly popular, but it worked (at least someone thought it), right?

Additionally, I re-implemented another branch using sqlite and the size of the driver is *huge*. The briefcase jar goes from 5MB to over 11MB with sqlite. The extra size is likely due to the native code, most of which won't even be used in a normal installation. For an internal database with 1 table containing 2 files, I'm not sure I'm sold that is a better option given its purpose.

We are arguing about the color of the bike shed. As long as a suitable database is used, and instance id lookup is O(lg n) - presumably using indexing - the issue will be fixed as it is in the PR.

**Comment by batkinson** [comment]
> If I'm understanding correctly, what would happen with the db change as written is that no downloaded submissions would be recognized after the Briefcase update because although the files would still exist, the DB records would no longer be recognized.

@lognaturel, yes this PR only fixes the acute issue. However, most of the reason download is painful are the three issues I just submitted PRs for. Also, those most affected are people with large data sets, which probably just don't use briefcase (over the net) right now. Though that's complete speculation. My point is that fixing these *significantly* improves the whole experience downloading, *especially* for those in resource-constrained environments.

>  Users would continue to have a stale info.db folder.

Yep, but even with a migration I probably wouldn't want to remove it. You really think people would be confused by it? How many people actually know what the existing one is for? I actually didn't until I needed to fix this.

**Comment by lognaturel** [comment]
I think @yanokwa was asking about the database choice to have a record of your rationale, not to second-guess it. The jar size difference alone is plenty compelling and I believe that's why smallsql was chosen initially.

As I understand it, many people use Briefcase to do incremental backups. That is, they pull records down once every N days to build up a local mirror of their data. They expect that the download will continue where it was left off and starting the download over could be a problem depending on available bandwidth, how they pay for it, etc.

For the migration, I was imagining using a preference to keep track of whether the DB layer has been changed yet or not. If a check on load shows it hasn't, then the hsql dbs for each form could be built up with some kind of "update in progress" dialog blocking user interaction. The smallsql `info.db` folder could stay there as it's not very big. I guess it would be helpful in the case where someone goes down to an earlier version of Briefcase.

@batkinson If someone built that migration on a branch off this one, would you be willing to do a verification pass?

**Comment by batkinson** [comment]
Hi @lognaturel. Ah ok. Yeah, hopefully my explanation made it clear; no big reason, almost any would do and so I used one I that I had cached locally to save the download. Given the limited use and the obscurity of smallsql I figured almost anything was better as long as it didn't make deployment more difficult. My apologies if my response seemed overly defensive.

> @batkinson If someone built that migration on a branch off this one, would you be willing to do a verification pass?

Sure. So, I actually did a quick pass at a basic working solution. I can just push it to this PR. If someone wants to improve on it, I can take a look.

**Comment by batkinson** [comment]
To whomever reviews, apologies for the long list of commits, but this was a bit of a slog due to the state of the code. Anyway, I tried to keep the commits small so you can review easily. Note that there will now be a small conflict (easily resolved) if applying the scale fixes (#138, #140, and #141) together.

**Comment by lognaturel** [comment]
Super thoughtful migration implementation. Thanks so much, @batkinson!

In terms of manual verification, I looked at the following:
- existing smallsql db for a particular form -- info.hsqldb folder is created, info.db is moved to info.db.bak; downloads resume where expected (and much faster than before)
- form that has never been pulled before -- info.hsqldb folder created as expected; downloads resume where expected on subsequent pulls
- Briefcase running twice, `unable to open form database: Database lock acquisition failure` is shown

File: src/org/opendatakit/briefcase/util/DatabaseUtils.java [hunk 1]
```diff
@@ -95,6 +90,17 @@ private void assertRecordedInstanceTable() throws SQLException {
     }
   }
 
+  private void dumpRecordedInstanceTable() throws SQLException {
+    try (Statement stmt = connection.createStatement()) {
+      stmt.execute(SELECT_ALL_SQL);
+      try (ResultSet rs = stmt.getResultSet()) {
+        while (rs.next()) {
+          log.debug("recorded: " + rs.getString(1) + " @dir=" + rs.getString(2));
```
Comment (lognaturel) [inline src/org/opendatakit/briefcase/util/DatabaseUtils.java]: @batkinson you mentioned quickly that you had noticed the return of a slowdown and I think it was based on this logging, is that right? The issue being that `isDebugEnabled` always true?

With my setup, I can't seem to get these debug statements to show up at all although `isDebugEnabled` does evaluate to true. If I put a `log.error` I can see it, though. In other classes, info messages show up at my IntelliJ console. I'm having a tough time following how logging is intended to work. @batkinson, if you're around for a quick chat in #briefcase-code, it might be helpful to talk live for a minute and strategize on how to approach getting more sane logging both for performance and general improvements.

Comment (batkinson) [inline src/org/opendatakit/briefcase/util/DatabaseUtils.java]: >The issue being that isDebugEnabled always true?

You got it exactly. Something with the logging setup smells off.
