### PR TITLE
Provide a human-friendly error message

### LINKED ISSUE #380: Provide a human-friendly error message for MissingArgumentException in CLI
#### Software versions 
Briefcase v1.9.0-88-g42264c07

#### Problem description
When an argument is missing in CLI mode, the user gets a stack trace.

#### Steps to reproduce the problem
`java -jar build/libs/ODK\ Briefcase\ v1.9.0-88-g42264c07 -pa -id foo -sd ../ -url test -u -p`

#### Expected behavior
The user gets a friendly message about missing values.

### PR DESCRIPTION
**Pull request by emajj**
Provide human-friendly error message for MissingArgumentException in CLI

Closes #380

#### What has been done to verify that this works as intended?
`./gradlew check` runs successfully

#### Are there any risks to merging this code? If so, what are they?
None

### CODE REVIEW

**Comment by ggalmazor** [comment]
Hi @emajj! It's important we all use the PR creation template and specify what specific tests we have made to know our PR works and solves the problem, what other alternatives have we considered and if there is any risk on merging the PR.

Could you update the PR description with this information, please?

File: src/org/opendatakit/common/cli/Cli.java [hunk 1]
```diff
@@ -136,6 +137,10 @@ private CommandLine getCli(String[] args, Set<Param> params) {
       printHelp(requiredOperations, operations);
       System.exit(1);
       return null;
+    } catch (MissingArgumentException e) {
+      System.err.println("Error: " + e.getMessage());
```
Comment (ggalmazor) [inline src/org/opendatakit/common/cli/Cli.java]: Redact a more user-friendly message like "Missing value on argument -u"

**Comment by emajj** [comment]
@ggalmazor thanks for the review. I actually deleted the template contents. How can I get it back?

**Comment by ggalmazor** [comment]
You have it on `.github/PULL_REQUEST_TEMPLATE.md`
