### PR TITLE
Briefcase should work behind a proxy network

### LINKED ISSUE #86: Can/Should briefcase be usable behind a proxy
I'm trying to connect to http://opendatakit.appspot.com/ behind a proxy server. Getting following stack-trace. I suspect this is due to the proxy. 

Is briefcase suppose to work behind a proxy?

```
org.apache.http.conn.HttpHostConnectException: Connect to opendatakit.appspot.com:80 [opendatakit.appspot.com/74.125.138.153, opendatakit.appspot.com/2607:f8b0:4002:c0c:0:0:0:99] failed: Network is unreachable (connect failed)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at org.opendatakit.briefcase.util.AggregateUtils.testServerConnectionWithHeadRequest(AggregateUtils.java:554)
        at org.opendatakit.briefcase.util.ServerUploader.testServerUploadConnection(ServerUploader.java:391)
        at org.opendatakit.briefcase.util.ServerConnectionTest.run(ServerConnectionTest.java:41)
        at org.opendatakit.briefcase.ui.ServerConnectionDialog.actionPerformed(ServerConnectionDialog.java:204)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.Component.processMouseEvent(Component.java:6533)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6298)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
        at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
        at java.awt.Dialog.show(Dialog.java:1084)
        at java.awt.Component.show(Component.java:1671)
        at java.awt.Component.setVisible(Component.java:1623)
        at java.awt.Window.setVisible(Window.java:1014)
        at java.awt.Dialog.setVisible(Dialog.java:1005)
        at org.opendatakit.briefcase.ui.PushTransferPanel$DestinationActionListener.actionPerformed(PushTransferPanel.java:132)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.Component.processMouseEvent(Component.java:6533)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6298)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.net.ConnectException: Network is unreachable (connect failed)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
```

### PR DESCRIPTION
**Pull request by daveycrockett**
Fixes #86 

See previous pull request (https://github.com/opendatakit/briefcase/pull/105) for conversation to-date, and how to test.

I made the proxy settings auto-save...if either port or host field loses focus, the settings will auto-update.  I also made the text field for port only allow numbers, so there's no longer a need for a validation pop-up.  Wasn't sure how to handle an empty host value, suggestions welcome.  For now it'll just error out when it attempts to use a hostless proxy, which isn't great, but if someone's entering in proxy settings you have to hope they know what they're doing well enough to put a host name in?

Thanks to @rclakmal for implementing the vast majority of this fix!

### CODE REVIEW

File: src/org/opendatakit/briefcase/model/BriefcasePreferences.java [hunk 1]
```diff
@@ -112,6 +114,16 @@ public static String getBriefcaseDirectoryProperty() {
     return Preference.APPLICATION_SCOPED.get(BriefcasePreferences.BRIEFCASE_DIR_PROPERTY,
         System.getProperty("user.home"));
   }
+
+  public static void setBriefcaseProxyProperty(HttpHost value) {
+    if (value == null) {
+	  Preference.APPLICATION_SCOPED.remove(BRIEFCASE_PROXY_HOST_PROPERTY);
```
Comment (lognaturel) [inline src/org/opendatakit/briefcase/model/BriefcasePreferences.java]: Should be spaces, not tabs. I think there are a few more places where tabs are introduced. Would be great to do a pass replacing them!

File: src/org/opendatakit/briefcase/ui/MessageStrings.java [hunk 2]
```diff
@@ -73,4 +73,15 @@
...
+  
+  public static final String PROXY_HOST = "Host";
+  public static final String PROXY_PORT = "Port";
+  public static final String PROXY_TOGGLE = "Use Proxy";
+  public static final String GENERAL_SETTINGS_STRING =
+		  "<HTML><U>General Settings</U></HTML>";
+  public static final String PROXY_SETTINGS_STRING =
+		  "<HTML><U>Proxy Settings</U></HTML>";
+  public static final String PROXY_SET_ADVICE =
+		  ". If you are behind a proxy, try setting up your proxy details through 'Settings' tab.";
```
Comment (yanokwa) [inline src/org/opendatakit/briefcase/ui/MessageStrings.java]: This will result in two periods if you enter the wrong user name and password. It'll say "Please verify that the URL, your user credentials and your permissions are all correct.."

File: src/org/opendatakit/briefcase/model/BriefcasePreferences.java [hunk 3]
```diff
@@ -143,4 +155,15 @@ public Preferences preferenceFactory(Class<?> node) {
     private static final BriefcasePreferences APPLICATION_SCOPED =
         new BriefcasePreferences(BriefcasePreferences.class, PreferenceScope.APPLICATION);
   }
+ 
+  public static HttpHost getBriefCaseProxyConnection() {
+	  String host = Preference.APPLICATION_SCOPED.get(
+			  BriefcasePreferences.BRIEFCASE_PROXY_HOST_PROPERTY,null);
+	  if(host != null){
```
Comment (yanokwa) [inline src/org/opendatakit/briefcase/model/BriefcasePreferences.java]: Add an extra space after if

File: src/org/opendatakit/briefcase/ui/SettingsPanel.java [hunk 4]
```diff
@@ -88,6 +171,46 @@ public void actionPerformed(ActionEvent e) {
...
+    class ProxyToggleListener implements ActionListener {
+
+        @Override
+        public void actionPerformed(ActionEvent e) {
+        	if (e.getSource() == chkProxy) {
+        		if (chkProxy.isSelected()) {
+        			txtHost.setEnabled(true);
+        			txtPort.setEnabled(true);
+        			if (!StringUtils.isNotEmptyNotNull(txtPort.getText())) {
+        				txtPort.setText("80");
```
Comment (yanokwa) [inline src/org/opendatakit/briefcase/ui/SettingsPanel.java]: Default HTTP proxy port is 8080.

**Comment by yanokwa** [comment]
@daveycrockett Thanks for taking on this issue. I really like the elegance of the auto save on focus. Nice and clean!

I can confirm that the basic case of connecting to the proxy works. The things I'd like to see improved as far as the UX.
* For an empty host, what would you think about defaulting to `127.0.0.1`?
* I think we should remove the General Settings and Proxy Settings labels. I don't think they add much.
* I did a quick look into Java UI standards (and what IntelliJ/Android Studio do with proxies), and I think we should re-jigger this layout. Namely, the label should come to the right of the checkbox, and if we are doing that, it makes sense to indent the host name and port number. And then make the text boxes expand relative to the size of the window. Attached is a quick mockup. 
proxy
* Maybe `Use HTTP Proxy` is a better title and if we can do one of these fancy number only widgets, that'd be lovely.
   portnumber

**Comment by daveycrockett** [comment]
@lognaturel it looks as if the HttpClient object in ServerConnectionInfo is instantiated/set once when I connect to an aggregate server, meaning that if I change settings in between connection and pulling individual form submissions, the changes to proxy settings wouldn't be reflected.  Easiest (read: laziest) way to fix this would be to create a new HttpClient every time we interact with the server, i.e. ServerConnectionInfo.getHttpClient() always calls WebUtils.createHttpClient() with each invocation.  Only other way I can think to do this would be to have settings changes trigger unsetting httpClient in any ServerConnectionInfo objects that are lying around (perhaps promoting httpClient to a static member of the class, or something).  Thoughts?  Without a major refactor I think the lazy option may be the only feasible thing, but I defer to the expertise of others more familiar with briefcase.

**Comment by daveycrockett** [comment]
Went ahead and implemented the lazy initializer for httpClient, and incorporated all the other feedback.  Thanks @yanokwa and @lognaturel!  Agree that a lot of the files need a formatting pass to get tabs/spaces consistent, I opted to keep that separate so that the diff is hopefully readable.  If/when this is merged, I'd opt to do a second PR just for formatting.
