### PR TITLE
Fix #379. CLI unexpected error directed to Slack.

### LINKED ISSUE #379: CLI unexpected error message should direct users to Slack and help them find log
#### Software versions 
Briefcase v1.9.0-88-g42264c07

#### Problem description
Unexpected errors currently result in the following message:
```
Briefcase unexpected error. Please review the logs and contact maintainers on the following URLs:
	https://opendatakit.slack.com/messages/C374LNDK9/
	https://forum.opendatakit.org/c/support
```

#### Steps to reproduce the problem
In this version, specify a date with a format other than yyyy-mm-dd

#### Expected behavior
The message should be something like
```
Briefcase unexpected error. Please review briefcase.log for more information. For help, post to https://forum.opendatakit.org/c/support
```

In general, the forum is a better place for user support. Also, it's important to let the user know where the log is located.

Does the proposed message make sense to others?

### PR DESCRIPTION
**Pull request by jaketripp**
Closes #379.

#### What has been done to verify that this works as intended?
Searched for the old error message and updated the two files that included it. 

#### Why is this the best possible solution? Were any other approaches considered?
No other approaches considered - seemed like a straightforward error to solve.

#### Are there any risks to merging this code? If so, what are they?
No known risks.

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.

### CODE REVIEW

File: src/org/opendatakit/briefcase/ui/BriefcaseCLI.java [hunk 1]
```diff
@@ -85,9 +85,7 @@ public void run() {
       log.error("Error", e);
       System.exit(1);
     } catch (Throwable t) {
-      System.err.println("Unexpected error. Please review the logs and contact maintainers on the following URLs:");
-      System.err.println("\thttps://opendatakit.slack.com/messages/C374LNDK9/");
-      System.err.println("\thttps://forum.opendatakit.org/c/support");
+      System.err.println("Briefcase unexpected error. Please review briefcase.log for more information. For help, post to https://forum.opendatakit.org/c/support");
```
Comment (yanokwa) [inline src/org/opendatakit/briefcase/ui/BriefcaseCLI.java]: I think the first part of this would read better as: "Unexpected error in Briefcase"

I think it'd also be able to provide a little more information about where the user can find briefcase.log. @ggalmazor  where is that file stored on the release builds?

**Comment by jaketripp** [comment]
@yanokwa I completely understand. To be clear, is this the message you want?

"Unexpected error in Briefcase. Please review briefcase.log for more information. For help, post to https://forum.opendatakit.org/c/support"

After searching the repository for "briefcase.log" it is listed in the .gitignore, which makes me think it's generated when there is an error, and not tracked by git, and it gets placed in the root of the repository after being created. If I've gotten all of those assumptions right, I think a supplying a path to briefcase.log wouldn't be very helpful.

**Comment by yanokwa** [comment]
@jaketripp I think that message is perfect!

And it looks like the question I had is answered at https://github.com/opendatakit/briefcase#logging-tests-vs-development-vs-release.

> ...logs to a `briefcase.log` file, created in the same folder where Briefcase is launched by the user.

**Comment by jaketripp** [comment]
@yanokwa Great! Should I include that the briefcase.log file is "created in the same folder where Briefcase is launched by the user"? I think they'll see it, so I vote no.

**Comment by yanokwa** [comment]
Looking forward to your next PR, @jaketripp!
