### PR TITLE
Issue 657 Fix adding csv extension when given filename doesn't include it

### LINKED ISSUE #657: Fix adding csv extension when given filename doesn't include it
#### Software versions 
Briefcase v1.12.0

#### Problem description

As discussed in [this forum post](https://forum.opendatakit.org/t/csv-file-extension-missing-on-export-via-odk-briefcase-cli-1-12/15449), v1.10 ensured that the main export file included the csv, in case the user provided a filename without it.

#### Steps to reproduce the problem
- Run the JAR: `java -jar build/libs/ODK-Briefcase-v1.12.1.jar -e -id all-widgets -ed /tmp/coco -f chuchu -sd /home/guillermo`
  (note that the `-f` arg defined a filename without the `csv` extension)

#### Expected behavior
The exported main CSV file should have `csv` extension.

#### Other information 
N/A

### PR DESCRIPTION
**Pull request by ggalmazor**
Closes #657

#### What has been done to verify that this works as intended?
Add and run a new automated test that ensures the filename has the `csv` extension.
Manually run the JAR to verify it works.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

This PR fixes a regression introduced in v1.11

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
No.

### CODE REVIEW

**Comment by ggalmazor** [comment]
It would be great to have a review of this issue to release a v1.12.2 with the fix this week.

File: src/org/opendatakit/briefcase/export/ExportConfiguration.java [hunk 1]
```diff
@@ -449,7 +447,7 @@ public Path getExportMediaPath() {
   }
 
   public Optional<String> getExportFileName() {
-    return exportFileName;
+    return exportFileName.map(filename -> filename.endsWith(".csv") ? filename : filename + ".csv");
```
Comment (dcbriccetti) [inline src/org/opendatakit/briefcase/export/ExportConfiguration.java]: Might there be upper or mixed case “csv”?

Comment (ggalmazor) [reply src/org/opendatakit/briefcase/export/ExportConfiguration.java]: Good point. I’ll take that into account

**Comment by ggalmazor** [comment]
@dcbriccetti, I've added new test cases to ensure we don't add extra extensions when the user provides some uppercase variant of `.csv`.
