### PR TITLE
Fix test overwriting user preferences

### LINKED ISSUE #275: Unknown default Storage Location on MacOS.
#### Software versions 
Briefcase v1.8, Java v1.8. operating system MacOS,

#### Problem description
Weird problem displayed to me, default storage location was different (probably non-existing folder)  than I've chosen before. I was able to change it and the only way to reproduce the problem for me was starting briefcase again.  

#### Steps to reproduce the problem
1. Create new folder
2. Clone there briefcase code from github
3. Build an app
4. Run the app and go to Settings

#### Expected behavior
Default storage location should equal to the last chosen one when run briefcase or window when you can choose it should display.

#### Other information 
Pull from aggregate succeed but I couldn't find where pulled forms are. Screenshot attached:
mac

### PR DESCRIPTION
**Pull request by ggalmazor**
Closes #275 

This PR changes the Export tab to rely on the `FormCache` instead of reading the filesystem in search of form files.

This enables us to:
- ignore any concern regarding the Briefcase Storage directory, which is managed in an appScoped user preferences node.
- easily create an in-memory `FormCacheable` test double for our tests

#### What has been done to verify that this works as intended?
Starting with a well configured and running Briefcase app on my machine:
- Run `./gradlew build` without skipping the tests
- Run `java -jar build/libs/ODK[...].jar`
- Confirm that the Briefcase Storage dir is intact
- Confirm that the rest of functionality on the Export tab still works.

Also, automated test.

#### Why is this the best possible solution? Were any other approaches considered?
N/A

#### Are there any risks to merging this code? If so, what are they?
N/A

### CODE REVIEW

File: src/org/opendatakit/briefcase/util/FormCacheble.java [hunk 1]
```diff
@@ -1,5 +1,6 @@
 package org.opendatakit.briefcase.util;
```
Comment (dcbriccetti) [inline src/org/opendatakit/briefcase/util/FormCacheble.java]: `FormCacheable` would be a better spelling for this class.

See this, for example:
https://docs.oracle.com/javaee/6/api/javax/persistence/Cacheable.html

Comment (ggalmazor) [reply src/org/opendatakit/briefcase/util/FormCacheble.java]: It's French and it's pronounced "casheblé"

I'm kidding. Let's fix that typo!

File: test/java/org/opendatakit/briefcase/util/InMemoryFormCache.java [hunk 2]
```diff
@@ -0,0 +1,37 @@
+package org.opendatakit.briefcase.util;
+
+import java.util.ArrayList;
+import java.util.HashMap;
+import java.util.List;
+import java.util.Map;
+import org.opendatakit.briefcase.model.BriefcaseFormDefinition;
+
+public class InMemoryFormCache implements FormCacheable {
+  private final Map<String, String> hashes = new HashMap<>();
```
Comment (dcbriccetti) [inline test/java/org/opendatakit/briefcase/util/InMemoryFormCache.java]: With map names, I like to give more information about the keys and values, especially since `<String, String>` tells us little. Here I would say `hashesByFormName` or something like that.

File: test/java/org/opendatakit/briefcase/util/InMemoryFormCache.java [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+  private final Map<String, BriefcaseFormDefinition> forms = new HashMap<>();
```
Comment (dcbriccetti) [inline test/java/org/opendatakit/briefcase/util/InMemoryFormCache.java]: I suggest a name like `formsByName`.

File: src/org/opendatakit/briefcase/util/FileSystemUtils.java [hunk 4]
```diff
@@ -62,7 +62,7 @@
 
   static final Log log = LogFactory.getLog(FileSystemUtils.class);
 
-  private static FormCacheble formCache = new NullFormCache();
```
Comment (dcbriccetti) [inline src/org/opendatakit/briefcase/util/FileSystemUtils.java]: I wish the formCache weren’t here in FileSystemUtils, but it doesn’t bother me terribly.

Comment (ggalmazor) [reply src/org/opendatakit/briefcase/util/FileSystemUtils.java]: Oh, that bothers me a lot, it's on my top 10 list of things I can't wait to put my hands on! :D

**Comment by kkrawczyk123** [comment]
Hi @ggalmazor, Tested this branch on Ubuntu and MacOS. On Ubuntu build was successful but I got error when tried to open an app using java -jar command. Screenshot attached:
pr302 fail_linux
And on MacOS build failed. When I used command without executing tests, build was successful and and I saw weird storage location. I closed briefcase and removed java user preferences and reboot. I tried run briefcase again and it didn't open at all like on ubuntu, screenshot attached:
pr302 fail_mac

**Comment by ggalmazor** [comment]
Thanks!

Did you clear preferences after building and before running Briefcase?

Also, could you copy here the text from the errors you got, please?

**Comment by ggalmazor** [comment]
> You have text from errors on attached screenshots.

Next time, please, add the text to the issue, not a screenshot. Having the text makes everything simpler because we can copy it and analyze the stacktraces. 

Having screenshots is nice but is not as useful.

**Comment by kkrawczyk123** [comment]
**Error from Ubuntu:**
[AWT-EventQueue-1] INFO com.brsanthu.googleanalytics.GoogleAnalytics - Initializing Google Analytics with config=GoogleAnalyticsConfig [threadNameFormat=googleanalytics-thread-{0}, enabled=true, maxThreads=1, useHttps=true, validate=true, httpUrl=http://www.google-analytics.com/collect, httpsUrl=https://ssl.google-analytics.com/collect, userAgent=java/1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12/Oracle Corporation/OpenJDK 64-Bit Server VM/Linux/4.13.0-31-generic/amd64, proxyPort=80, deriveSystemParameters=true, gatherStats=false] and defaultRequest=Request [parms={DOCUMENT_ENCODING=UTF-8, PROTOCOL_VERSION=1, HIT_TYPE=pageview, USER_LANGUAGE=en-US, CLIENT_ID=40a732d7-a740-4412-83d4-9b3f468d40d4, TRACKING_ID=UA-91951913-3}, customDimensions={}, customMetrics={}]
[AWT-EventQueue-1] ERROR org.opendatakit.aggregate.parser.BaseFormParserForJavaRosa - failed to launch app
java.lang.IllegalStateException: Duplicate key org.opendatakit.briefcase.model.FormStatus@666f65a5
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1254)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.opendatakit.briefcase.export.ExportForms.rebuildIndex(ExportForms.java:177)
	at org.opendatakit.briefcase.export.ExportForms.<init>(ExportForms.java:33)
	at org.opendatakit.briefcase.export.ExportForms.load(ExportForms.java:50)
	at org.opendatakit.briefcase.ui.export.ExportPanel.from(ExportPanel.java:108)
	at org.opendatakit.briefcase.ui.MainBriefcaseWindow.<init>(MainBriefcaseWindow.java:233)
	at org.opendatakit.briefcase.ui.MainBriefcaseWindow.<init>(MainBriefcaseWindow.java:54)
	at org.opendatakit.briefcase.ui.MainBriefcaseWindow$1.run(MainBriefcaseWindow.java:179)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.GNOME.Accessibility.AtkWrapper$5.dispatchEvent(AtkWrapper.java:700)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ggalmazor** [comment]
Thanks!

**Comment by ggalmazor** [comment]
I've just updated the repo with a fix for the error you showed. 

I've also recorded a video to show how I test it on my machine... https://www.youtube.com/watch?v=gws7ES-IZXY

**Comment by ggalmazor** [comment]
By the way, `java -version` gives me this:

```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

**Comment by ggalmazor** [comment]
I did another screen recording on a mac. I see that there are two tests failing and we're dealing with that on PR #308 

The important thing is that running the tests doesn't mess up your user preferences, affecting Briefcase.

The video: https://www.youtube.com/watch?v=uL1YzujtaME

**Comment by kkrawczyk123** [comment]
@ggalmazor, I've already tested it in the same way as you did on Ubuntu and Mac. Great job! It looks like this pull request is fixing the problem. Briefcase finally asks about choosing storage location.

**Comment by ggalmazor** [comment]
Finally! Thanks for the help :)

I'm going to test in on win10 too just to be sure.

**Comment by kkrawczyk123** [comment]
I will do it too but on win8, as soon as I finish whole testing process on ubuntu. (I have both systems on the same machine)

**Comment by ggalmazor** [comment]
Hi! In my win10 machine, there's a test failing, but this is going to be solved by #315
