### PR TITLE
Fix #352 - Bulk exporting more than one encrypted form fails.

### LINKED ISSUE #352: Bulk exporting more than one encrypted form fails
#### Software versions 
Briefcase v1.9.9, Java v1.8.0_161, Linux (Debian Buster)

#### Problem description
When the user selects more than one encrypted forms for export, there's a filesystem concurrency problem and only one form is successfully exported.

#### Steps to reproduce the problem
Select more than one encrypted forms and try to export. **The selected forms have to be at least one encrypted submission.**

#### Expected behavior
All forms should be exported successfully (given correct confs)

#### Other information 
Stacktrace:
```
[ForkJoinPool-1-worker-4] ERROR org.opendatakit.briefcase.util.FileSystemUtils - Error decrypting:submission.xml.enc
java.io.FileNotFoundException: /tmp/.temp/submission.xml (No existe el archivo o el directorio)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.opendatakit.briefcase.util.FileSystemUtils.decryptFile(FileSystemUtils.java:466)
	at org.opendatakit.briefcase.util.FileSystemUtils.decryptSubmissionFiles(FileSystemUtils.java:566)
	at org.opendatakit.briefcase.util.FileSystemUtils.decryptAndValidateSubmission(FileSystemUtils.java:754)
	at org.opendatakit.briefcase.util.ExportToCsv.processInstance(ExportToCsv.java:877)
	at org.opendatakit.briefcase.util.ExportToCsv.doAction(ExportToCsv.java:176)
	at org.opendatakit.briefcase.export.NewExportAction.export(NewExportAction.java:83)
	at org.opendatakit.briefcase.ui.export.ExportPanel.lambda$export$11(ExportPanel.java:161)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[ForkJoinPool-1-worker-4] INFO org.opendatakit.briefcase.util.ExportToCsv - Error decrypting submission uuid47450daa-ae51-4d9a-a3b6-3b43118eb514 Cause: org.opendatakit.briefcase.model.FileSystemException: Error decrypting:submission.xml.enc Cause: java.io.FileNotFoundException: /tmp/.temp/submission.xml (No existe el archivo o el directorio)
```

It seems like the two threads try to read and remove the same temp dir while decrypting submissions?

You can use these forms:
- [encrypted-form-1.xml.txt](https://github.com/opendatakit/briefcase/files/1702660/encrypted-form-1.xml.txt) - [private-key-1.txt](https://github.com/opendatakit/briefcase/files/1702661/private-key-1.txt)
- [encrypted-form-2.xml.txt](https://github.com/opendatakit/briefcase/files/1702662/encrypted-form-2.xml.txt) - [private-key-2.txt](https://github.com/opendatakit/briefcase/files/1702665/private-key-2.txt)

### PR DESCRIPTION
**Pull request by mayank8318**
Closes #352 

#### What has been done to verify that this works as intended?
Created two encrypted forms as mentioned in the issue.
Made entries using Collect and uploaded to the server.
Successfully exported both the forms together.

#### Why is this the best possible solution? Were any other approaches considered?
This is the simplest and probably the most efficient way of doing it. Could have made the method synchronized but that will take away the multi-threading advantage - speed.

#### Are there any risks to merging this code? If so, what are they?
None that I am aware of.

### CODE REVIEW

File: src/org/opendatakit/briefcase/util/ExportToCsv.java [hunk 1]
```diff
@@ -790,34 +793,25 @@ private boolean processInstance(File instanceDir) {
...
-          EventBus.publish(new ExportProgressEvent(msg, briefcaseLfd));
-          return false;
-        }
-      }
-
-      if (!unEncryptedDir.mkdirs()) {
+      unEncryptedDir = null;
+      try {
+        Path path = Files.createTempDirectory(Paths.get(outputDir.getAbsolutePath()), ".temp");
+        unEncryptedDir = new File(path.toString());
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/util/ExportToCsv.java]: This should be `path.toFile()`

File: src/org/opendatakit/briefcase/util/ExportToCsv.java [hunk 2]
```diff
@@ -790,34 +793,25 @@ private boolean processInstance(File instanceDir) {
...
-          EventBus.publish(new ExportProgressEvent(msg, briefcaseLfd));
-          return false;
-        }
-      }
-
-      if (!unEncryptedDir.mkdirs()) {
+      unEncryptedDir = null;
+      try {
+        Path path = Files.createTempDirectory(Paths.get(outputDir.getAbsolutePath()), ".temp");
+        unEncryptedDir = path.toFile();
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/util/ExportToCsv.java]: This line shouldn't be on the try, because it doesn't throw any exception

File: src/org/opendatakit/briefcase/util/ExportToCsv.java [hunk 3]
```diff
@@ -790,34 +793,25 @@ private boolean processInstance(File instanceDir) {
...
-          log.warn(msg, e);
-          EventBus.publish(new ExportProgressEvent(msg, briefcaseLfd));
-          return false;
-        }
-      }
-
-      if (!unEncryptedDir.mkdirs()) {
+      unEncryptedDir = null;
+      try {
+        Path path = Files.createTempDirectory(Paths.get(outputDir.getAbsolutePath()), ".temp");
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/util/ExportToCsv.java]: We are refactoring everything we can to Java NIO2 artifacts... let's avoid using strings for everything and change `outputDir.getAbsolutePath()` to `outputDir.toURI()`. (Look those uppercase chars, @dcbriccetti! :open_mouth:)

Also, you're using `".temp"` as prefix, but that looks more like a suffix. I think that `"decryption"` would work there.

File: src/org/opendatakit/briefcase/util/ExportToCsv.java [hunk 4]
```diff
@@ -790,34 +793,25 @@ private boolean processInstance(File instanceDir) {
...
+        unEncryptedDir = path.toFile();
+      } catch (IOException e) {
         EventBus.publish(new ExportProgressEvent("Unable to create temp directory: "
-            + unEncryptedDir.getAbsolutePath(), briefcaseLfd));
+                + unEncryptedDir.getAbsolutePath(), briefcaseLfd));
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/util/ExportToCsv.java]: Let's improve this event a little bit by adding a cause to the message like in line 828: 
```java
EventBus.publish(new ExportProgressEvent(msg + " Cause: " + e.toString(), briefcaseLfd));
```

Until we refactor error handling, it's the only way we can detect that an `ExportProgressEvent` comes with some negative outcome.

**Comment by ggalmazor** [comment]
By the way @mayank8318, could you check if those temp dirs are deleted after? If they're not, please, file an issue to remember that we need to do something there.

**Comment by mayank8318** [comment]
@ggalmazor these are being deleted thanks to the finally block! 😁

File: src/org/opendatakit/briefcase/util/ExportToCsv.java (hunk 3 above)
Comment (mayank8318) [reply src/org/opendatakit/briefcase/util/ExportToCsv.java]: I am using `".temp"` to hide it since earlier also the directory was `".temp"`. Should I refactor it to `"decryption"` or `".decryption"`

File: src/org/opendatakit/briefcase/util/ExportToCsv.java (hunk 4 above)
Comment (mayank8318) [reply src/org/opendatakit/briefcase/util/ExportToCsv.java]: :+1:

File: src/org/opendatakit/briefcase/util/ExportToCsv.java (hunk 3 above)
Comment (ggalmazor) [reply src/org/opendatakit/briefcase/util/ExportToCsv.java]: Oh, ok! Then, leave it like that :)

Although that won't work on Windows...

File: src/org/opendatakit/briefcase/util/ExportToCsv.java [hunk 5]
```diff
@@ -790,34 +793,34 @@ private boolean processInstance(File instanceDir) {
...
-        // silently delete it...
-        try {
-          FileUtils.deleteDirectory(unEncryptedDir);
-        } catch (IOException e) {
-          String msg = "Unable to delete stale temp directory: " + unEncryptedDir.getAbsolutePath();
-          log.warn(msg, e);
-          EventBus.publish(new ExportProgressEvent(msg, briefcaseLfd));
-          return false;
-        }
+      unEncryptedDir = null;
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/util/ExportToCsv.java]: IntelliJ tells me that this line can be removed

File: src/org/opendatakit/briefcase/util/ExportToCsv.java [hunk 6]
```diff
@@ -790,34 +793,34 @@ private boolean processInstance(File instanceDir) {
...
+      Path path = null;
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/util/ExportToCsv.java]: IntelliJ tells me that the `= null` assignation is redundant and can be removed

File: src/org/opendatakit/briefcase/util/ExportToCsv.java [hunk 7]
```diff
@@ -790,34 +793,34 @@ private boolean processInstance(File instanceDir) {
...
+      try {
+        path = Files.createTempDirectory(Paths.get(outputDir.toURI()), ".temp");
+      } catch (IOException e) {
+        String msg = "Unable to get path of temp directory.";
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/util/ExportToCsv.java]: I think this should say "Unable to create temp directory."

File: src/org/opendatakit/briefcase/util/ExportToCsv.java [hunk 8]
```diff
@@ -790,34 +793,34 @@ private boolean processInstance(File instanceDir) {
...
+        log.error(msg, e);
+        EventBus.publish(new ExportProgressEvent(msg + " Cause : "
+                + e.toString(), briefcaseLfd));
+        return false;
       }
 
-      if (!unEncryptedDir.mkdirs()) {
+      unEncryptedDir = path.toFile();
+      if (!unEncryptedDir.exists()) {
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/util/ExportToCsv.java]: I think this whole `if` block is redundant and can be removed. I mean, if we get to this line, we can assume that the `Files.createTempDirectory` has worked.

**Comment by ggalmazor** [comment]
@opendatakit-bot label "needs testing"

**Comment by kkrawczyk123** [comment]
**Tested with success!**
@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by ggalmazor** [comment]
@mayank8318 solve the merging conflicts and I think this is ready to go :)

**Comment by mayank8318** [comment]
@ggalmazor Done :)

**Comment by ggalmazor** [comment]
Thanks, @mayank8318, now it's ready to be merged :)

**Comment by ggalmazor** [comment]
@opendatakit-bot unlabel "needs review"
@opendatakit-bot label "reviewed"
