### PR TITLE
Issue 544 make submissions directory filter less restrictive

### LINKED ISSUE #544: Export to CSV results in empty CSV
#### Software versions 
Briefcase v1.11.0

#### Problem description
Exporting to CSV in v1.11.0 results in a CSV with just the headers.

#### Steps to reproduce the problem
* Clear prefs
* Import from Collect odk storage folders
* Export to CSV

#### Expected behavior
Export CSV has more than header rows.

#### Other information 
Briefcase v1.10 works great, so this is a bug introduced in v1.11

### PR DESCRIPTION
**Pull request by ggalmazor**
Closes #544

This PR changes the filter Briefcase uses when listing the contents of the instances folder of a form to retrieve the submissions to be exported. Before this change, we would expect a particular format that would leave out forms using arbitrary instanceIDs and forms pulled from ODK Collect directories.

Now, the filter will reject only non-directory entries and hidden directories (directories starting with a `.` character are hidden in mac and linux computers)

#### What has been done to verify that this works as intended?
- Pull a form with submissions from an ODK Collect directory and export it. 
- Artificially add a `.DS_Store` directory inside the instances folder of the pulled form and add an empty `submission.xml` file in it.
- Verify that all submissions are present and no errors are logged

I've also improved the unit test suite that covers the directory filter with new test cases for this.

#### Why is this the best possible solution? Were any other approaches considered?
This is the narrowest fix I could come with

#### Are there any risks to merging this code? If so, what are they?
Nope.

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
Nope.

### CODE REVIEW

**Comment by yanokwa** [comment]
I think only you can launch a rebuild.

**Comment by ggalmazor** [comment]
CircleCI complains about not having write permission...

**Comment by ggalmazor** [comment]
Nevermind, I've just fixed a typo in one commit. That will launch the build again

File: test/java/org/opendatakit/briefcase/reused/UncheckedFilesIsInstanceDirTest.java [hunk 1]
```diff
@@ -55,13 +55,6 @@ public void a_file_is_not_an_instance_directory() {
     assertThat(isInstanceDir(someFile), is(false));
   }
 
-  @Test
-  public void an_arbitrary_named_directory_is_not_an_instance_directory() {
-    assertThat(isInstanceDir(createDirectories(tempDir.resolve("cocotero"))), is(false));
```
Comment (yanokwa) [inline test/java/org/opendatakit/briefcase/reused/UncheckedFilesIsInstanceDirTest.java]: Odd choice of variable name, but I guess this is a Spanish thing?

File: src/org/opendatakit/briefcase/reused/UncheckedFiles.java [hunk 2]
```diff
@@ -218,11 +218,9 @@ public static long checksumOf(Path file) {
 
   public static boolean isInstanceDir(Path dir) {
     return Files.isDirectory(dir)
-        // Instance directories follow the pattern "uuid01234567-0123-0123-0123-012345678901"
-        // ("uuid" followed by a UUID string)
-        // This is decided when forms are pulled and written into the storage directory
-        // TODO Extract into an artifact, test, and use everywhere where this convention is used
-        && dir.getFileName().toString().matches("^uuid[\\w]{8}-[\\w]{4}-[\\w]{4}-[\\w]{4}-[\\w]{12}$")
+        // Ignore hidden max/linux hidden folders
```
Comment (yanokwa) [inline src/org/opendatakit/briefcase/reused/UncheckedFiles.java]: s/max/mac

File: test/java/org/opendatakit/briefcase/reused/UncheckedFilesIsInstanceDirTest.java (hunk 1 above)
Comment (ggalmazor) [reply test/java/org/opendatakit/briefcase/reused/UncheckedFilesIsInstanceDirTest.java]: Are you referring to "cocotero"? I can change that to something more neutral. I use cocotero when I don't want to think about a name and it doesn't really matter but I try to change that after. This one slipped through.

Comment (ggalmazor) [reply test/java/org/opendatakit/briefcase/reused/UncheckedFilesIsInstanceDirTest.java]: OK, changed it. 

By the way, cocotero means coconut tree.

**Comment by kkrawczyk123** [comment]
Looks good on Ubuntu but MacOS and Windows don't allow me to create `.DS_Store` directory how can I cheat on them :) ?

**Comment by ggalmazor** [comment]
> Looks good on Ubuntu but MacOS and Windows don't allow me to create .DS_Store directory how can I cheat on them :) ? 

I think there's no need to test that on windows, since the filter is especifically for hidden folders in mac/linux. As far as I know, Windows hosts don't create such folders that could get in the way and produce a failure.

**Comment by kkrawczyk123** [comment]
Ok, sure.
@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
