### PR TITLE
Issue 512 Fix remember passwords checkbox behavior

### LINKED ISSUE #512: Forms are not pulled when `Pull before export` option is selected
**EDIT!**
A new bug which can cause this problem:
1. The user opens Briefcase and **does not select** `remember the password`
2. The user connects to aggregate and pulls one form
3. The user goes to `Export` tab and chooses `Export directory`
4. The user exports this one form
5. `Pull before export` checkbox is **ACTIVE**

#### Software versions 
Briefcase v1.11.0
Operating system: Linux, Windows, macOS
**REGRESSION - worked on ODKBriefcasev1.10.1-151gf61342b**

#### Problem description
Forms are not pulled when `Pull before export` option is selected

#### Steps to reproduce the problem
1. The user pulls one form
2. The user exports this form
3. The user fills this form on Collect and sends to Aggregate - make sure that form is visible on Aggregate
4. The user selects `Pull before export` and clicks on `Export` button

 5. The new submission was not added to CSV - pull before export does not work

#### Expected behavior
The form is pulled and newest submissions are visible in export file

### PR DESCRIPTION
**Pull request by ggalmazor**
- Now it stays disabled after exporting if the remember passwords setting is not checked
- Now it is unchecked if the user revokes the consent to remember passwords to avoid seeing it checked and disabled

Closes #512

#### What has been done to verify that this works as intended?
Manually tested in the UI

#### Why is this the best possible solution? Were any other approaches considered?
Passing the preference downstream is the narrowest fix I can come up with.

#### Are there any risks to merging this code? If so, what are they?
Nope.

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
Nope.

### CODE REVIEW

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanel.java [hunk 1]
```diff
@@ -96,7 +97,8 @@ private void triggerOnChange() {
     onChangeCallbacks.forEach(Runnable::run);
   }
 
-  public void setEnabled(boolean enabled) {
+  public void setEnabled(boolean enabled, boolean savePasswordsConsent) {
```
Comment (dcbriccetti) [inline src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanel.java]: Does this method now do more than setting an enabled state?

**Comment by kkrawczyk123** [comment]
Tested on all three systems. On all three I obtained the same results:
When I run briefcase - pull before export wasn't active - I go to remember password checkbox and set it - pull before export was enabled and worked correctly.
But I when I didn't set remember password checkbox - pull before export wasn't active - I exported some random form and it enabled pull before export - I was able to choose it - pull before export didn't work which is good that it did not work - but it can give the user the wrong impression so we must fix it.
@ggalmazor @ln @yanokwa 
@opendatakit-bot unlabel "needs testing"

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanel.java (hunk 1 above)
Comment (ggalmazor) [reply src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanel.java]: It just needs more information to set the enabled state. When the savePasswordsConsent is `false`, the remember password checkbox must be disabled.

I use the `setEnabled` method because it's present in all `JComponents` and it felt right, but in this case, it's more like a `lockUI` that prevents/enables user interaction.

**Comment by ggalmazor** [comment]
Sorry, @kkrawczyk123! Long story short, I accidentally broke the fix while fixing a test. Now it should work as advertised.
