### PR TITLE
Issue #806 Metadata files should have relative paths

### LINKED ISSUE #806: Metadata files should contain relative file paths
#### Problem description
Current code in master generates `metadata.json` files with absolute paths to the form files, which make them not portable. Any path should be relative to the briefcase directory.

#### Steps to reproduce the problem
1. Pull a form and close Briefcase
2. Move the SD to another location
3. Open Briefcase and change the storage location directory in the settings tab.
4. Try to export the form

You should see that Briefcase freezes and there's an error in the logs

#### Expected behavior
Briefcase shouldn't freeze or fail.

### PR DESCRIPTION
**Pull request by ggalmazor**
Closes #806

#### What has been done to verify that this works as intended?
Fixed and run the automated tests
Manually pulled forms, changed the sd location, and exported them

#### Why is this the best possible solution? Were any other approaches considered?
This is the smallest change I could come up to be able to store relative paths while providing absolute paths to downstream code.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
No risks here, just a fixed bug :)

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
Nope.

### CODE REVIEW

File: src/org/opendatakit/briefcase/model/form/FileSystemFormMetadataAdapter.java [hunk 1]
```diff
@@ -55,19 +57,21 @@ public FormMetadataPort syncWithFilesAt(Path storageRoot) {
     Stream<Path> formFiles = candidateFormFiles.filter(path -> isAForm(XmlElement.from(path)));
 
     // Parse existing metadata.json files or build new FormMetadata from form files
-    Stream<FormMetadata> metadataFiles = formFiles.map(formFile -> {
+    // At this point, we collect the stream to avoid problems coming
+    // from actually writing files in the same folders we're reading from
```
Comment (dcbriccetti) [inline src/org/opendatakit/briefcase/model/form/FileSystemFormMetadataAdapter.java]: What sort of problems?

Comment (ggalmazor) [reply src/org/opendatakit/briefcase/model/form/FileSystemFormMetadataAdapter.java]: Classic reading stuff that you're writing to. The adapter scans, reads and writes the same files in the same stream.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Ubuntu, MacOS and Windows.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
