### PR TITLE
Issue 493 Restore lost analytics tracking of pull/push tabs

### LINKED ISSUE #493: Only export process is tracked on Google Analytics.
#### Software versions 
Briefcase v1.10.x, Java v1.x.x, operating system: all

#### Problem description
Pull and push processes are not visible on Google Analytics.

#### Steps to reproduce the problem
Pull/push some forms and track real-time actions on Google Analytics.

#### Expected behavior
All processes pull/push/export should be tracked 

#### Other information 
Export is tracked properly.

### PR DESCRIPTION
**Pull request by ggalmazor**
Closes #493

#### What has been done to verify that this works as intended?
Compiled and run Briefcase.
Debugged to ensure analytics code was exercised when entering/leaving tabs

#### Why is this the best possible solution? Were any other approaches considered?
This is just code that was lost on some merge

#### Are there any risks to merging this code? If so, what are they?
Nope.

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
Nope

### CODE REVIEW

File: src/org/opendatakit/briefcase/ui/pull/PullPanel.java [hunk 1]
```diff
@@ -52,13 +53,14 @@
   private TerminationFuture terminationFuture;
   private Optional<Source<?>> source = Optional.empty();
 
-  public PullPanel(PullPanelForm view, PullForms forms, BriefcasePreferences tabPreferences, BriefcasePreferences appPreferences, TerminationFuture terminationFuture) {
+  public PullPanel(PullPanelForm view, PullForms forms, BriefcasePreferences tabPreferences, BriefcasePreferences appPreferences, TerminationFuture terminationFuture, Analytics analytics) {
```
Comment (dcbriccetti) [inline src/org/opendatakit/briefcase/ui/pull/PullPanel.java]: I think I’d rather see `ComponentListener analyticsComponentListener` than the whole `Analytics` object passed in, but not a big deal.

Comment (ggalmazor) [reply src/org/opendatakit/briefcase/ui/pull/PullPanel.java]: OK, we can discuss that after getting rid of all implicit coupling on global artifacts. There's still hidden stuff around... 

I'm for passing each top-level artifact the least number of dependencies on their minimal possible form.

**Comment by kkrawczyk123** [comment]
I am not sure if this issue has been fixed, as the only tracking result I obtained was export on Windows.
