### PR TITLE
Fix #323 - Add date range limit to date pickers.

### LINKED ISSUE #323: Set proper date range values for start and end date
#### Software versions 
Briefcase vv1.8.0-227-gbebd3f5, Java v1.8, Ubuntu, Aggregate v1.x.x, Collect v1.x.x...

#### Problem description
There is no restriction of the date range values in the start date and end date datepickers.

#### Steps to reproduce the problem
Open any datepicker.

#### Expected behavior
The start date should not exceed current date and when a particular start date is selected, the end date values less than the start date should be disabled instead of giving an error message afterwards.

#### Other information 
Set appropriate date range in the DatePickerProperties.

Can I work on this issue?

### PR DESCRIPTION
**Pull request by mayank8318**
Closes #323 

#### What has been done to verify that this works as intended?
Built and ran the program.

#### Why is this the best possible solution? Were any other approaches considered?
It is best to disable end date till you enter start date, thus eliminating one logical error.

#### Are there any risks to merging this code? If so, what are they?
I tested for all possible logical scenarios that I could think of and it works.

### CODE REVIEW

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java [hunk 1]
```diff
@@ -74,12 +73,15 @@
     startDatePicker = createDatePicker();
     endDatePicker = createDatePicker();
     $$$setupUI$$$();
+    startDatePicker.getSettings().setDateRangeLimits(null, LocalDate.now());
+    startDatePicker.setDateToToday();
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: I think we shouldn't set the default start date to any value...

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java [hunk 2]
```diff
@@ -74,12 +73,15 @@
...
     startDatePicker.getSettings().setGapBeforeButtonPixels(0);
     startDatePicker.getComponentDateTextField().setPreferredSize(exportDirField.getPreferredSize());
     startDatePicker.getComponentToggleCalendarButton().setPreferredSize(exportDirChooseButton.getPreferredSize());
     endDatePicker.getSettings().setGapBeforeButtonPixels(0);
     endDatePicker.getComponentDateTextField().setPreferredSize(exportDirField.getPreferredSize());
     endDatePicker.getComponentToggleCalendarButton().setPreferredSize(exportDirChooseButton.getPreferredSize());
+    endDatePicker.setEnabled(false);
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: This changes previous behavior, where we let the user select an end date **before** a start date.

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java [hunk 3]
```diff
@@ -89,26 +91,14 @@
...
-    });
-    endDatePicker.addDateChangeListener(event -> {
-      if (!isDateRangeValid()) {
-        showError(MessageStrings.INVALID_DATE_RANGE_MESSAGE, "Export configuration error");
-        endDatePicker.clear();
-      } else
-        onSelectEndDateCallbacks.forEach(consumer -> consumer.accept(extractDate(event)));
+      endDatePicker.setEnabled(true);
+      endDatePicker.getSettings().setDateRangeLimits(extractDate(event), null);
+      setEndDate(extractDate(event));
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: Updating the end date could pass unnoticed by the user and feels a little bit weird even when you are setting trying to set a date after the established end date

**Comment by mayank8318** [comment]
@ggalmazor Sorry, realised that now. Will update the PR soon.

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java (hunk 1 above)
Comment (mayank8318) [reply src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: ok but it has to be before the current date right?

**Comment by ggalmazor** [comment]
Awesome, thanks! I'm on Slack should you need help on anything ;)

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java (hunk 2 above)
Comment (mayank8318) [reply src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: But then we were checking for empty start date during submission anyways, so why not disable the end date itself till the user sets a start date?

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java (hunk 3 above)
Comment (mayank8318) [reply src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: Ok then I will clear it? Is that fine?

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java (hunk 1 above)
Comment (ggalmazor) [reply src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: That makes sense but I wonder if we could have problems with forms pulled from different time zones... Maybe a form is from a timezone with a positive offset that effectively marks it as being created "in the future" respect to the host's timezone.

We can sit on this one and wait for feedback from @lognaturel or @yanokwa to confirm this bit.

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java (hunk 2 above)
Comment (ggalmazor) [reply src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: I'm ok with disabling it, but I think it's worth to mention that this changes behavior, just to be sure that we're all ok with this change... 

I don't really know if users want to set the end before the start, but it's supported on the current version. It might be safe to change it, though.

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java (hunk 3 above)
Comment (ggalmazor) [reply src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: Maybe the best option would be to clear the end date only if it's before the start date we're trying to set. What do you think?

**Comment by ggalmazor** [comment]
Also, remove the unused  `ConfigurationPanelForm.showError()` method [commit line here](https://github.com/opendatakit/briefcase/pull/326/commits/7fd90248b9d07b49291b65ff8e6c35339f4cc0d6?diff=unified#diff-9014a675cb101d05fd895ad99eab07d5R175), please

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java (hunk 3 above)
Comment (mayank8318) [reply src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: That situation wont be possible as such dates would be disabled already.

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java (hunk 1 above)
Comment (mayank8318) [reply src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: Okay

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java (hunk 3 above)
Comment (ggalmazor) [reply src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: Hmmm... If I set start to `2018-01-01`, the end date to `2018-01-20`, then I can set the start to `2018-01-30`, producing the situation I'm talking about. Then I would clear the end field.

If the second time I set the start date to `2018-01-10` instead, I wouldn't do anything, because the date range is valid.

Comment (mayank8318) [reply src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: Oh okay sorry didn't think of this. Yes, this I will handle and clear the end date.

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java [hunk 4]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (C) 2018 Nafundi
+ * Copyright (C) 2017 Nafundi
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java]: This should read 2018

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java [hunk 5]
```diff
@@ -68,20 +70,32 @@ public void choose_pem_file_button_is_swapped_for_a_clean_button_that_cleans_the
...
+    component.setStartDate(LocalDate.of(2017,1,27));
+    assertEquals(component.endDatePicker().getDate(), null);
+  }
+
+  @Test
+  public void new_start_date_is_before_or_on_end_date_is_valid() {
+    component.setStartDate(LocalDate.of(2017,1,20));
+    component.setEndDate(LocalDate.of(2017,1,25));
+    component.setStartDate(LocalDate.of(2017,1,24));
+    assertEquals(component.endDatePicker().getDate(), LocalDate.of(2017,1,25));
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java]: Please, change these `assertEquals` to `assertThat(actualValue, is(expectedValue))` like the on the rest of the test suite.

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java [hunk 6]
```diff
@@ -156,6 +152,10 @@ private void clearPemFile() {
     pemFileClearButton.setVisible(false);
   }
 
+  private boolean isInvalidStartDate(LocalDate date) {
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: I'd suggest renaming this to `isAfterEndDate(LocalDate date)`

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java [hunk 7]
```diff
@@ -89,26 +90,21 @@
...
-        showError(MessageStrings.INVALID_DATE_RANGE_MESSAGE, "Export configuration error");
-        startDatePicker.clear();
-      } else
-        onSelectStartDateCallbacks.forEach(consumer -> consumer.accept(extractDate(event)));
-    });
-    endDatePicker.addDateChangeListener(event -> {
-      if (!isDateRangeValid()) {
-        showError(MessageStrings.INVALID_DATE_RANGE_MESSAGE, "Export configuration error");
+
+      if (event.getNewDate() == null || isInvalidStartDate(extractDate(event)))
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: Every call to `extractDate(event)` could be replaced by `event.getNewDate()` because now the datepicker returns a `java.time.LocalDate` directly (we were using an old version before that used a third party library for dates).

As a result, the `extractDate` method could be removed.

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java [hunk 8]
```diff
@@ -89,26 +90,21 @@
...
         endDatePicker.clear();
-      } else
-        onSelectEndDateCallbacks.forEach(consumer -> consumer.accept(extractDate(event)));
+
+      endDatePicker.setEnabled(event.getNewDate() != null);
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: If you're up for that, all these `null` checks could be replaced by using a little bit of `Optional<LocalDate> startDate = Optional.ofNullable(event.getNewDate())`, but we can do that on a future PR as well.

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java [hunk 9]
```diff
@@ -68,20 +70,32 @@ public void choose_pem_file_button_is_swapped_for_a_clean_button_that_cleans_the
...
   }
-}
\ No newline at end of file
+
+  @Test
+  public void clear_end_date_when_new_start_date_is_after_end_date() {
+    component.setStartDate(LocalDate.of(2017,1,22));
+    component.setEndDate(LocalDate.of(2017,1,25));
+    component.setStartDate(LocalDate.of(2017,1,27));
+    assertEquals(component.endDatePicker().getDate(), null);
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java]: Please, change this with with `assertThat(value, is(nullValue()));`

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java [hunk 10]
```diff
@@ -68,20 +70,32 @@ public void choose_pem_file_button_is_swapped_for_a_clean_button_that_cleans_the
...
+  }
+
+  @Test
+  public void new_start_date_is_before_or_on_end_date_is_valid() {
+    component.setStartDate(LocalDate.of(2017,1,20));
+    component.setEndDate(LocalDate.of(2017,1,25));
+    component.setStartDate(LocalDate.of(2017,1,24));
+    assertEquals(component.endDatePicker().getDate(), LocalDate.of(2017,1,25));
+    component.setStartDate(LocalDate.of(2017,1,25));
+    assertEquals(component.endDatePicker().getDate(), LocalDate.of(2017,1,25));
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java]: Same here: `assertThat(actualValue, is(expectedValue))`

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java [hunk 11]
```diff
@@ -68,20 +70,32 @@ public void choose_pem_file_button_is_swapped_for_a_clean_button_that_cleans_the
...
   }
 
   @Test
-  public void shows_error_and_clears_field_after_inserting_an_invalid_end_date() {
-    component.setStartDate(LocalDate.of(2020, 1, 1));
-    component.setEndDate(LocalDate.of(2018, 1, 1));
-    assertThat(component.errorDialog(500), is(GenericUIMatchers.visible()));
-    component.acceptErrorDialog();
-    assertThat(component.endDateField(), is(empty()));
+  public void empty_start_date_end_datepicker_is_disabled() {
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java]: I'd suggest renaming the method to something more like an English phrase 
`end_datepicker_is_disabled_if_the_start_datepicker_is_empty`

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java [hunk 12]
```diff
@@ -68,20 +70,32 @@ public void choose_pem_file_button_is_swapped_for_a_clean_button_that_cleans_the
   }
 
   @Test
-  public void shows_error_and_clears_field_after_inserting_an_invalid_start_date() {
-    component.setEndDate(LocalDate.of(2018, 1, 1));
-    component.setStartDate(LocalDate.of(2020, 1, 1));
-    assertThat(component.errorDialog(500), is(GenericUIMatchers.visible()));
-    component.acceptErrorDialog();
-    assertThat(component.startDateField(), is(empty()));
+  public void cannot_insert_an_invalid_end_date() {
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java]: I'd suggest renaming this to explicitly tell the condition which makes impossible to insert an invalid date: `cannot_insert_an_end_date_after_the_established_start_date` or something like that

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java [hunk 13]
```diff
@@ -68,20 +70,32 @@ public void choose_pem_file_button_is_swapped_for_a_clean_button_that_cleans_the
...
-    assertThat(component.endDateField(), is(empty()));
+  public void empty_start_date_end_datepicker_is_disabled() {
+    component.startDatePicker().clear();
+    assertFalse(component.endDatePicker().isEnabled());
   }
-}
\ No newline at end of file
+
+  @Test
+  public void clear_end_date_when_new_start_date_is_after_end_date() {
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java]: Rename `end_date_is_cleared_when_the_new_start_date_is_after_it`

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java [hunk 14]
```diff
@@ -68,20 +70,32 @@ public void choose_pem_file_button_is_swapped_for_a_clean_button_that_cleans_the
...
+    component.setStartDate(LocalDate.of(2017,1,22));
+    component.setEndDate(LocalDate.of(2017,1,25));
+    component.setStartDate(LocalDate.of(2017,1,27));
+    assertEquals(component.endDatePicker().getDate(), null);
+  }
+
+  @Test
+  public void new_start_date_is_before_or_on_end_date_is_valid() {
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java]: Rename: `end_date_remains_unchanged_if_it_is_after_the_new_start_date`

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java [hunk 15]
```diff
@@ -65,31 +66,37 @@ public void it_initializes_UI_fields_with_values_from_the_initial_configuration(
   }
 
   @Test
-  public void shows_an_error_and_resets_the_field_when_the_UI_tries_to_set_a_date_range_end_that_is_before_its_start() {
+  public void cannot_insert_an_invalid_end_date() {
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java]: I think these tests are safe to remove because the UI tests on `ConfigurationPanelTest` are easier to understand and they're testing the same things...

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java [hunk 16]
```diff
@@ -65,31 +66,37 @@ public void it_initializes_UI_fields_with_values_from_the_initial_configuration(
...
-    ConfigurationPanel panel = new ConfigurationPanel(ExportConfiguration.empty(), view);
-    view.setStartDate(LocalDate.of(2019, 1, 1));
+    view.setStartDate(LocalDate.of(2017, 1, 30));
+    assertFalse(view.endDatePicker.isDateAllowed(LocalDate.of(2017, 1, 28)));
+  }
 
-    // Trigger the error
-    view.setEndDate(LocalDate.of(2018, 1, 1));
+  @Test
+  public void empty_start_date_end_datepicker_is_disabled() {
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java]: Suggest removing test

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java [hunk 17]
```diff
@@ -65,31 +66,37 @@ public void it_initializes_UI_fields_with_values_from_the_initial_configuration(
...
+    FakeConfigurationPanelForm view = new FakeConfigurationPanelForm(false);
+    view.startDatePicker.clear();
+    assertFalse(view.endDatePicker.isEnabled());
+  }
 
-    assertThat(view.errorShown, is(true));
+  @Test
+  public void clear_end_date_when_new_start_date_is_after_end_date() {
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java]: Suggest removing test

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java [hunk 18]
```diff
@@ -65,31 +66,37 @@ public void it_initializes_UI_fields_with_values_from_the_initial_configuration(
...
+    view.setStartDate(LocalDate.of(2017,1,22));
+    view.setEndDate(LocalDate.of(2017,1,25));
+    view.setStartDate(LocalDate.of(2017,1,27));
     assertThat(view.endDatePicker.getDate(), nullValue());
-    assertThat(panel.getConfiguration().getEndDate(), isEmpty());
   }
 
   @Test
-  public void shows_an_error_and_resets_the_field_when_the_UI_tries_to_set_a_date_range_start_that_is_after_its_end() {
+  public void new_start_date_is_before_or_on_end_date_is_valid() {
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java]: Suggest removing test

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java (hunk 7 above)
Comment (mayank8318) [reply src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: Done

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java (hunk 6 above)
Comment (mayank8318) [reply src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: Done

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java (hunk 4 above)
Comment (mayank8318) [reply test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java]: Done

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java (hunk 12 above)
Comment (mayank8318) [reply test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java]: Renamed to `cannot_insert_an_end_date_before_the_set_start_date`

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java (hunk 11 above)
Comment (mayank8318) [reply test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java]: Renamed to `end_datepicker_is_disabled_if_the_start_datepicker_is_empty`

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java (hunk 13 above)
Comment (mayank8318) [reply test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java]: Done

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java (hunk 9 above)
Comment (mayank8318) [reply test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java]: Done

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java (hunk 5 above)
Comment (mayank8318) [reply test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java]: Done

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java (hunk 14 above)
Comment (mayank8318) [reply test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java]: Done

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java (hunk 10 above)
Comment (mayank8318) [reply test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java]: Done

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java (hunk 15 above)
Comment (mayank8318) [reply test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java]: Ok

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java (hunk 16 above)
Comment (mayank8318) [reply test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java]: Done

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java (hunk 17 above)
Comment (mayank8318) [reply test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java]: :+1:

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java (hunk 18 above)
Comment (mayank8318) [reply test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java]: :+1:

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java (hunk 8 above)
Comment (mayank8318) [reply src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: I guess a new PR for that would be apt since it is a different issue :)

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java [hunk 19]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (C) 2018 Nafundi
+ * Copyright (C) 2017 Nafundi
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelUnitTest.java]: Should read 2018

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java [hunk 20]
```diff
@@ -89,26 +88,19 @@
...
-    endDatePicker.addDateChangeListener(event -> {
-      if (!isDateRangeValid()) {
-        showError(MessageStrings.INVALID_DATE_RANGE_MESSAGE, "Export configuration error");
+
+      if (event.getNewDate() != null && isAfterEndDate(event.getNewDate()))
         endDatePicker.clear();
-      } else
-        onSelectEndDateCallbacks.forEach(consumer -> consumer.accept(extractDate(event)));
+
+      if (event.getNewDate() != null)
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: You can remove the `if` block and directly set the date range limits with whatever comes in `event.getNewDate()` This way, when the user clears the field, the restriction is lifted.

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java [hunk 21]
```diff
@@ -89,26 +88,19 @@
...
-        showError(MessageStrings.INVALID_DATE_RANGE_MESSAGE, "Export configuration error");
-        startDatePicker.clear();
-      } else
-        onSelectStartDateCallbacks.forEach(consumer -> consumer.accept(extractDate(event)));
-    });
-    endDatePicker.addDateChangeListener(event -> {
-      if (!isDateRangeValid()) {
-        showError(MessageStrings.INVALID_DATE_RANGE_MESSAGE, "Export configuration error");
+
+      if (event.getNewDate() != null && isAfterEndDate(event.getNewDate()))
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: Don't clear the field. Let's go for only applying restrictions to datepickers :)

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java [hunk 22]
```diff
@@ -89,26 +88,19 @@
...
+
+      onSelectStartDateCallbacks.forEach(consumer -> consumer.accept(event.getNewDate()));
     });
-  }
 
-  private boolean isDateRangeValid() {
-    LocalDate startDate = startDatePicker.getDate();
-    LocalDate endDate = endDatePicker.getDate();
-    return startDate == null || endDate == null || startDate.isBefore(endDate);
+    endDatePicker.addDateChangeListener(event -> onSelectEndDateCallbacks.forEach(consumer -> consumer.accept(event.getNewDate())));
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: On this change listener we're missing a `startDatePicker.getSettings().setDateRangeLimits(null, event.getNewDate());` to apply restrictions to the start datepicker.

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java [hunk 23]
```diff
@@ -89,26 +88,19 @@
...
-      if (!isDateRangeValid()) {
-        showError(MessageStrings.INVALID_DATE_RANGE_MESSAGE, "Export configuration error");
+
+      if (event.getNewDate() != null && isAfterEndDate(event.getNewDate()))
         endDatePicker.clear();
-      } else
-        onSelectEndDateCallbacks.forEach(consumer -> consumer.accept(extractDate(event)));
+
+      if (event.getNewDate() != null)
+        endDatePicker.getSettings().setDateRangeLimits(event.getNewDate().plusDays(1), null);
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: You don't have to add a day to the date because we need to be able to select the same day on both datepickers

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java [hunk 24]
```diff
@@ -156,6 +148,10 @@ private void clearPemFile() {
     pemFileClearButton.setVisible(false);
   }
 
+  private boolean isAfterEndDate(LocalDate date) {
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: After the changes above, this method will not be used. Remove.

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java [hunk 25]
```diff
@@ -68,20 +70,26 @@ public void choose_pem_file_button_is_swapped_for_a_clean_button_that_cleans_the
...
+    component.setStartDate(LocalDate.of(2017,1,22));
+    component.setEndDate(LocalDate.of(2017,1,25));
+    component.setStartDate(LocalDate.of(2017,1,27));
+    assertThat(component.endDatePicker().getDate(), is(nullValue()));
   }
-}
\ No newline at end of file
+
+  @Test
+  public void end_date_remains_unchanged_if_it_is_after_the_new_start_date() {
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java]: Remove this test

File: test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java [hunk 26]
```diff
@@ -68,20 +70,26 @@ public void choose_pem_file_button_is_swapped_for_a_clean_button_that_cleans_the
...
   }
 
   @Test
-  public void shows_error_and_clears_field_after_inserting_an_invalid_end_date() {
-    component.setStartDate(LocalDate.of(2020, 1, 1));
-    component.setEndDate(LocalDate.of(2018, 1, 1));
-    assertThat(component.errorDialog(500), is(GenericUIMatchers.visible()));
-    component.acceptErrorDialog();
-    assertThat(component.endDateField(), is(empty()));
+  public void end_date_is_cleared_when_the_new_start_date_is_after_it() {
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelTest.java]: Remove this test

**Comment by mayank8318** [comment]
image
@ggalmazor We don't need these pop us now right?

**Comment by ggalmazor** [comment]
> @ggalmazor We don't need these pop-ups now right?
That's right :)

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java [hunk 27]
```diff
@@ -89,28 +88,23 @@
...
+
     startDatePicker.addDateChangeListener(event -> {
-      if (!isDateRangeValid()) {
-        showError(MessageStrings.INVALID_DATE_RANGE_MESSAGE, "Export configuration error");
-        startDatePicker.clear();
-      } else
-        onSelectStartDateCallbacks.forEach(consumer -> consumer.accept(extractDate(event)));
+
+      if (event.getNewDate() != null)
+        endDatePicker.getSettings().setDateRangeLimits(event.getNewDate().plusDays(1), null);
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: This block should be the same as on the `endDatePicker`:
- `... setDateRangeLimits(event.getNewDate(), null)`
- No need for the `if/else` case, no need for adding 1 day to the date

**Comment by mayank8318** [comment]
:) More to follow ;)

**Comment by lognaturel** [comment]
@mayank8318, this is a nice usability improvement.

There's a strange glitch on macOS, java 1.8.0_112. If I pick a start date and then go back one month I end up with something like:
screen shot 2018-02-02 at 7 16 36 pm

I can reset the interface by hovering over the month or year at the top of the menu.

**Comment by mayank8318** [comment]
@lognaturel Sorry I don't have access to a Mac here.

**Comment by ggalmazor** [comment]
I've also reproduced that glitch on a mac with Java 1.8.0_161... 

The date picker comes from a third party library. I think we should at least file an issue. 

@yanokwa @lognaturel do you think we should wait to merge this PR until the glitch is solved on the date picker library?

**Comment by ggalmazor** [comment]
I think this issue is the same one we're experiencing: https://github.com/LGoodDatePicker/LGoodDatePicker/issues/61

A user is proposing a hack to solve it (basically triggering a MouseEntered on the year field to force a repaint)

**Comment by lognaturel** [comment]
Sounds fine to merge if it's Mac only! Let's wait for another round of manual verification and merge after 1.9.0 comes out.

**Comment by kkrawczyk123** [comment]
Everything looks good on Ubuntu and Windows, but on MacOS I encountered the same problem as @lognaturel.

**Comment by kkrawczyk123** [comment]
@opendatakit-bot unlabel "needs testing"
