### PR TITLE
Issue 651 fixed the busy cursor after error happens

### LINKED ISSUE #651: Busy cursor still display after the errors.
#### Software versions 
macOS 10.13.6 

#### Problem description
I'm trying to connect to the demo server (http://opendatakit.appspot.com), but I got a connections time out error, after click the "Yes" button, the cursor still busy in the dialog, it's uncomfortable.

image
image

#### Steps to reproduce the problem
1. Let the connection time out or other connection errors happen.
2. Close the error dialog and back to the connection dialog.
3. The connection busy cursor should disappear but it still active.

#### Expected behavior
The progress bar should be disappeared after the error happens.

#### Other information 
@opendatakit-bot claim

### PR DESCRIPTION
**Pull request by huangyz0918**
Closes #651 

#### What has been done to verify that this works as intended?
We set the cursor to waiting after click the connection button but forget to set it back when an error happens, it's a small improvement but makes the user more comfortable when backing to the configuration dialog. 

#### Why is this the best possible solution? Were any other approaches considered?
It's the best solution, and it's really simple.

### CODE REVIEW

File: src/org/opendatakit/briefcase/ui/reused/source/RemoteServerDialog.java [hunk 1]
```diff
@@ -60,6 +61,7 @@ private RemoteServerDialog(RemoteServerDialogForm form, RemoteServer.Test server
             }
           }
           form.unsetTestingConnection();
+          form.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/ui/reused/source/RemoteServerDialog.java]: Maybe I'm a little bit confused, but is this really needed here?

I mean, you're already dealing with changing to the wait cursor and back to the default cursor in the `RemoteServerDialogForm.java`.

Comment (huangyz0918) [reply src/org/opendatakit/briefcase/ui/reused/source/RemoteServerDialog.java]: Yes, but the changes in `RemoteServerDialogForm.java` only resolves the `BriefcaseException` and `MalformedURLException`, unexpected errors like `connection time out` cannot be covered. The change here is for those unexpected.

Comment (ggalmazor) [reply src/org/opendatakit/briefcase/ui/reused/source/RemoteServerDialog.java]: OK, I understand now, although we shouldn't really interact directly with the UI (use Swing stuff) outside the `*Form` classes. 

Do you think we could hide resetting the cursor inside the `RemoteServerDialogForm.unsetTestingConnection()` method?

Maybe even setting it to waiting in the `RemoteServerDialogForm.setTestingConnection()` method.

Comment (huangyz0918) [reply src/org/opendatakit/briefcase/ui/reused/source/RemoteServerDialog.java]: Haha, you're right, let me do the refactor and test now :)

**Comment by huangyz0918** [comment]
@ggalmazor No problem.

**Comment by ggalmazor** [comment]
Thanks, @huangyz0918! We'll merge this after testing :)

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Ubuntu, MacOS and Windows.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
