### PR TITLE
Issue 796 support custom functions

### LINKED ISSUE #796: XPathUnhandledException on export of forms using 3rd party client functions
#### Software versions 
- Briefcase v1.16.3
- Java v1.8.x
- Windows 10

#### Problem description
When doing an export, `XPathUnhandledException` occurs, causing Briefcase to hang indefinitely.

#### Steps to reproduce the problem
1. **XLSForm**: Convert to XML an XLSForm that has a custom functionality intended to be used by a 3rd party client, i.e. not ODK Collect, e.g. [JHU Collect](https://github.com/PMA-2020/collect).
2. **Aggregate**: Upload form def to aggregate
3. **Client**: Download, complete, and submit form using a 3rd party client
4. **Briefcase**: Load GUI via the CLI
5. **Briefcase**: Fetch submissions
6. **Briefcase**: Attempt to export
7. **Briefcase**: Observe error stacktrace in terminal window

#### Expected behavior
- When exporting, should not error / freeze / crash.
- Briefcase should only care about the submission data; should not care about implementation details of how that data was created.

#### Other information 
**The particular issue**
The JHU Collect feature causing this issue is `trim()`, which clears extraneous whitespace. I believe that ODK Collect now supports this in a somewhat new feature, `normalize-space()`. In any event, I suppose it doesn't matter the specific 3rd party feature that was used. I'm just thinking that it would be ideal if Briefcase did not fully parse / evaluate / validate the form definition during the export (or any) process, unless there is a need for it that I am not seeing.

**Stack trace**
```java
C:\Users\annro>java -jar Downloads\ODK-Briefcase-v1.16.3.jar
Exception in thread "Thread-4" java.lang.RuntimeException: Error evaluating field 'firstname': The problem was located in calculate expression for /FSQ/firstname
XPath evaluation: cannot handle function 'trim'
       at org.javarosa.core.model.LatestDagBase.evaluateTriggerable(LatestDagBase.java:139)
       at org.javarosa.core.model.LatestDagBase.doEvaluateTriggerables(LatestDagBase.java:63)
       at org.javarosa.core.model.Safe2014DagImpl.evaluateTriggerables(Safe2014DagImpl.java:366)
       at org.javarosa.core.model.Safe2014DagImpl.initializeTriggerables(Safe2014DagImpl.java:452)
       at org.javarosa.core.model.Safe2014DagImpl.initializeTriggerables(Safe2014DagImpl.java:430)
       at org.javarosa.core.model.FormDef.initializeTriggerables(FormDef.java:721)
       at org.javarosa.core.model.FormDef.initialize(FormDef.java:1306)
       at org.opendatakit.briefcase.export.FormDefinition.getFormControls(FormDefinition.java:148)
       at org.opendatakit.briefcase.export.FormDefinition.from(FormDefinition.java:142)
       at org.opendatakit.briefcase.ui.export.ExportPanel.lambda$export$10(ExportPanel.java:190)
       at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
       at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
       at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
       at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
       at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
       at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
       at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
       at java.util.stream.ReferencePipeline.forEach(Unknown Source)
       at org.opendatakit.briefcase.reused.job.JobsRunner.launchAsync(JobsRunner.java:63)
       at org.opendatakit.briefcase.reused.job.JobsRunner.launchAsync(JobsRunner.java:51)
       at org.opendatakit.briefcase.ui.export.ExportPanel.export(ExportPanel.java:217)
       at java.lang.Thread.run(Unknown Source)
Caused by: org.javarosa.xpath.XPathUnhandledException: The problem was located in calculate expression for /FSQ/firstname
XPath evaluation: cannot handle function 'trim'
       at org.javarosa.xpath.expr.XPathFuncExpr.eval(XPathFuncExpr.java:486)
       at org.javarosa.xpath.XPathConditional.evalRaw(XPathConditional.java:71)
       at org.javarosa.core.model.condition.Triggerable.evalRaw(Triggerable.java:219)
       at org.javarosa.core.model.condition.Recalculate.eval(Recalculate.java:63)
       at org.javarosa.core.model.condition.Triggerable.apply(Triggerable.java:152)
       at org.javarosa.core.model.LatestDagBase.evaluateTriggerable(LatestDagBase.java:125)
       ... 21 more
```

**Versions confirmed to work / not work w/ 3rd party xpath functions**
Working: 1.9.x
Not working: 1.16.3, 1.15.x

### PR DESCRIPTION
**Pull request by ggalmazor**
Closes #796 

Use this form to test the PR: [custom-function-form.txt](https://github.com/opendatakit/briefcase/files/3604685/custom-function-form.txt)

#### What has been done to verify that this works as intended?
Added an automated regression test

#### Why is this the best possible solution? Were any other approaches considered?
A brute force approach that used actual exception messages was considered to provide a quick&dirty solution that didn't require changes in JR, but we ultimately thought it was better to add a method in JR to provide fallback function handlers that would prevent the error from #796.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This should be a narrow change that only prevents the issue from #796

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
No.

### CODE REVIEW

File: test/java/org/opendatakit/briefcase/CustomFunctionTest.java [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+public class CustomFunctionTest {
+  private static Path getPath(String fileName) {
+    return Optional.ofNullable(PullFromAggregateIntegrationTest.class.getClassLoader().getResource("org/opendatakit/briefcase/" + fileName))
+        .map(url -> Paths.get(toURI(url)))
+        .orElseThrow(RuntimeException::new);
+  }
+
+  @Test
+  public void name() {
+    FormDefinition.from(getPath("custom-function-form.xml"));
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/CustomFunctionTest.java]: This is enough to reproduce the error

File: test/java/org/opendatakit/briefcase/CustomFunctionTest.java [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+  }
+
+  @Test
+  public void full_regression_test() throws IOException, BadFormDefinition {
```
Comment (ggalmazor) [inline test/java/org/opendatakit/briefcase/CustomFunctionTest.java]: Will complete the test once we have a deal on the solution

File: src/org/opendatakit/briefcase/export/FormDefinition.java [hunk 3]
```diff
@@ -173,6 +197,17 @@ public static FormDefinition from(BriefcaseFormDefinition briefcaseFormDefinitio
         .collect(toMap(FormDefinition::controlFqn, e -> e));
   }
 
+  private static List<TreeElement> getAllDescendants(TreeElement e) {
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/export/FormDefinition.java]: This could use `Stream.flatMap` like `XmlElement.flatten`. Will refactor if the overall solution is acceptable

File: src/org/opendatakit/briefcase/export/FormDefinition.java [hunk 4]
```diff
@@ -144,7 +150,25 @@ public static FormDefinition from(BriefcaseFormDefinition briefcaseFormDefinitio
   }
 
   private static Map<String, QuestionDef> getFormControls(FormDef formDef) {
-    formDef.getEvaluationContext().addFunctionHandler(DUMMY_PULLDATA_HANDLER);
+    Pattern p = Pattern.compile("^.+cannot handle function '(.+?)'.*$");
+    List<IFunctionHandler> customFunctionHandlers = getAllDescendants(formDef.getMainInstance().getRoot())
+        .stream()
+        .flatMap(e -> {
+          try {
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/export/FormDefinition.java]: This is inlined here to avoid confusing indirection at this moment. Will be refactored to a method if this solution gets traction.

File: src/org/opendatakit/briefcase/export/FormDefinition.java [hunk 5]
```diff
@@ -144,7 +150,25 @@ public static FormDefinition from(BriefcaseFormDefinition briefcaseFormDefinitio
...
+            formDef.triggerTriggerables(e.getRef(), true);
+            return Stream.empty();
+          } catch (Throwable t) {
+            return Stream.of(t.getMessage().split("\n"));
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/export/FormDefinition.java]: JavaRosa will create a message with two lines. Example: 
```
Exception in thread "Thread-4" java.lang.RuntimeException: Error evaluating field 'firstname': The problem was located in calculate expression for /FSQ/firstname
XPath evaluation: cannot handle function 'trim'
```

We could go for the function name directly to the second line, but then we need to account for other unexpected exceptions that could have less than two lines, etc.

This implementation is more abstract with the tradeoff of having to process more data, which feels fine.

**Comment by joeflack4** [comment]
Thanks so much for working on this! Glad there's also a regression test.
