### PR TITLE
At startup, ignore failure to connect to Aggregate server that is refusing connections

### LINKED ISSUE #590: Fails to start when Aggregate server refuses connection
#### Software versions 
Briefcase v1.11.0

#### Problem description
If Briefcase had been configured with an Aggregate server, and is later started with the server refusing connections, Briefcase fails to start.

Maybe fix like this?

screen shot 2018-07-26 at 9 51 26 pm

### PR DESCRIPTION
**Pull request by dcbriccetti**
Closes #590 

#### What has been done to verify that this works as intended?
I ran Briefcase and it started.

Edit: Testing instructions
- Ensure that "remember passwords" is enabled in the Settings tab
- Create a user for the test in Aggregate
- Configure a pull source with the Aggregate server & user credentials
- Exit Briefcase
- Revoke all granted permissions for the user in Aggregate
- Start Briefcase

Expected results:
- The version in master would write an error stacktrace in the logs and refuse to start. 
- The version from this PR should log the error and start normally. 
- The pull source should be filled in
- The forms list should be empty

#### Why is this the best possible solution? Were any other approaches considered?
It may not be, but does solve the immediate problem.

#### Are there any risks to merging this code? If so, what are they?
I don’t think so.

### CODE REVIEW

File: src/org/opendatakit/briefcase/ui/pull/PullPanel.java [hunk 1]
```diff
@@ -63,11 +63,15 @@ public PullPanel(TransferPanelForm view, TransferForms forms, BriefcasePreferenc
     getContainer().addComponentListener(analytics.buildComponentListener("Pull"));
 
     // Read prefs and load saved remote server if available
-    this.source = RemoteServer.readPreferences(tabPreferences).flatMap(view::preloadSource);
-    this.source.ifPresent(source -> {
-      forms.load(source.getFormList());
-      view.refresh();
-      updateActionButtons();
+    source = RemoteServer.readPreferences(tabPreferences).flatMap(view::preloadSource);
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/ui/pull/PullPanel.java]: Is this still happenning? I think `SourcePanel.preload(RemoteServer server)` deals with this:
```java
public Optional<Source<?>> preload(RemoteServer server) {
  try {
    Source source = getSource(server);
    source.set(server);
    triggerOnSource(source);
    return Optional.of(source);
  } catch (HttpException e) {
    log.warn("Can't preload source. Resetting view", e);
    reset();
    return Optional.empty();
  }
}
```

Comment (ggalmazor) [reply src/org/opendatakit/briefcase/ui/pull/PullPanel.java]: I think we need to review this whole workflow, though. It could be easier to follow or, at least have some comments that explain the sequence of events/invocations.

File: src/org/opendatakit/briefcase/ui/pull/PullPanel.java [hunk 2]
```diff
@@ -63,11 +63,15 @@ public PullPanel(TransferPanelForm view, TransferForms forms, BriefcasePreferenc
...
+    source.ifPresent(source -> {
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/ui/pull/PullPanel.java]: So, following my rationale from my first comment, what we should avoid is having something in `source` other than an `Optional.empty()` when the stored conf values won't produce a successful connection to the remote Aggregate server.

File: src/org/opendatakit/briefcase/ui/pull/PullPanel.java (hunk 1 above)
Comment (ggalmazor) [reply src/org/opendatakit/briefcase/ui/pull/PullPanel.java]: After looking a little more into this, it turns out that the behavior is not consistent depending on what happens with the HTTP request:
- If it timeouts, it will throw an `HttpException` and the change on this PR will prevent a program failure
- If the server responds with any non-success (2xx) status code, it won't fail but it will show an empty form list, which is really confusing.

Let's leave your `try/catch` but work a little bit more the `catch` part.
I'll open a new issue to remember we need to normalize the behavior when we get a `4xx` or a `5xx`.

File: src/org/opendatakit/briefcase/ui/pull/PullPanel.java [hunk 3]
```diff
@@ -63,11 +63,15 @@ public PullPanel(TransferPanelForm view, TransferForms forms, BriefcasePreferenc
...
+      try {
+        forms.load(source.getFormList());
+        view.refresh();
+        updateActionButtons();
+      } catch (Exception e) {
+        System.err.println(e.toString());
```
Comment (ggalmazor) [inline src/org/opendatakit/briefcase/ui/pull/PullPanel.java]: Since this code is only executed when we're in UI mode, log this error instead of using `System.err`.

Also, the side effects of this should be exactly the same as the callback for `view.onReset()` in line 87 (we want to forget about that server conf and reset the UI). Maybe extract to a method and reuse in both places?

File: src/org/opendatakit/briefcase/ui/pull/PullPanel.java (hunk 1 above)
Comment (ggalmazor) [reply src/org/opendatakit/briefcase/ui/pull/PullPanel.java]: After looking a little more into this, it turns out that the behavior is not consistent depending on what happens with the HTTP request:
- If it timeouts, it will throw an `HttpException` and the change on this PR will prevent a program failure
- If the server responds with any non-success (2xx) status code, it won't fail but it will show an empty form list, which is really confusing.

Let's leave your `try/catch` but work a little bit more the `catch` part.
I'll open a new issue to remember we need to normalize the behavior when we get a `4xx` or a `5xx`.

File: src/org/opendatakit/briefcase/ui/pull/PullPanel.java (hunk 3 above)
Comment (dcbriccetti) [reply src/org/opendatakit/briefcase/ui/pull/PullPanel.java]: Are you sure you want to discard the server configuration? What if it’s a temporary condition?

Comment (dcbriccetti) [reply src/org/opendatakit/briefcase/ui/pull/PullPanel.java]: Changing to logging:
`2018-08-12 18:57:18,570 [main] WARN  o.o.briefcase.ui.pull.PullPanel - Unable to get form list from http://localhost:8080: org.opendatakit.briefcase.reused.http.HttpException: Connection refused`

**Comment by dcbriccetti** [comment]
Are you sure you want to discard the server configuration? What if it’s a temporary condition?

Changed to logging:
`2018-08-12 18:57:18,570 [main] WARN o.o.briefcase.ui.pull.PullPanel - Unable to get form list from http://localhost:8080: org.opendatakit.briefcase.reused.http.HttpException: Connection refused`

**Comment by ggalmazor** [comment]
> Are you sure you want to discard the server configuration? What if it’s a temporary condition?

I think it's the less confusing than getting an empty list. What do you think, @yanokwa, @lognaturel?

**Comment by yanokwa** [comment]
Sorry about blocking on this. @lognaturel and I discussed this with @ggalmazor and we think the best way forward is..

1. Not throw the configuration away.
1. Send in a PR that adds refresh button to the UI. 

I'll leave @ggalmazor to file the issues and send in the PR :)

**Comment by ggalmazor** [comment]
@opendatakit-bot label "needs testing"

**Comment by ggalmazor** [comment]
Thanks, @dcbriccetti! Sorry for keeping you waiting so much time :P

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Ubuntu, MacOS and Windows.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
