### PR TITLE
Issue 424 improve spacing on cli

### LINKED ISSUE #424: Improve spacing in CLI when entering bad flag
#### Software versions 
Briefcase v1.9

#### Steps to reproduce the problem
Common CLI mistakes result in hard to read output.

```
$ java -jar build/libs/ODK\ Briefcase\ v1.9.0-131-ga42f932.jar -x
Unrecognized option: -x
2018-03-26 20:31:24,387 [main] ERROR org.opendatakit.common.cli.Cli - Error
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -x
	at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:360)
	at org.apache.commons.cli.DefaultParser.handleShortAndLongOption(DefaultParser.java:497)
	at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:243)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:81)
	at org.opendatakit.common.cli.Cli.getCli(Cli.java:155)
	at org.opendatakit.common.cli.Cli.run(Cli.java:109)
	at org.opendatakit.briefcase.Launcher.main(Launcher.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Usage: java -jar briefcase.jar <params>

Available operations:
-c,--clear_prefs                    Clear saved preferences
-e,--export                         Export a form
```

```
$ java -jar build/libs/ODK\ Briefcase\ v1.9.0-131-ga42f932.jar -pla
2018-03-26 20:33:14,798 [main] ERROR o.o.a.p.BaseFormParserForJavaRosa - form_id and storage_directory are required
usage: java -jar briefcase.jar
 -ed,--export_directory </path/to/dir>                   Directory to
                                                         export the CSV
                                                         and media files
                                                         into (relative
                                                         path unless it
                                                         begins with / or
                                                         C:\)
```

It's really hard for a human to read these messages. I think there need to be a few improvements.

1. There should be consistent usage text. The first is title case and has a newline while the second is lower case and does not. Usage text should always have a line break before and after so it's easy to read.
1. Stack traces when you type the wrong flag seems unfriendly. I say just print the error and leave the stacktraces out of it!

### PR DESCRIPTION
**Pull request by ggalmazor**
Closes #424, #451, #450, #452, and #453 

This PR introduces changes aimed to ensure we use the new CLI's features as much as possible when the fallback, legacy CLI launcher is run. This happens when the user doesn't add the new operation flags we use on the new Launcher. Specifically
- Ensure that we parse command line args once
- Ensure that the `MainBriefcaseWindow` will use the new CLI's `printHelp()` method

It's important that we use the new CLI's `printHelp()` method show because we want to help users running the legacy launcher to migrate their scripts to the new one.

Also, the new CLI's `printHelp()` method uses more relaxed settings that won't clutter text if the console is too narrow.

#### What has been done to verify that this works as intended?
Run Briefcase's command line operations (both new and legacy)

#### Why is this the best possible solution? Were any other approaches considered?
Setting wider console settings on the legacy CLI launcher would probably have been a simpler solution, but I consider that that wouldn't support our bet for a new launcher.

#### Are there any risks to merging this code? If so, what are they?
Nope

### CODE REVIEW

**Comment by ggalmazor** [comment]
OK!

**Comment by kkrawczyk123** [comment]
Regression has been found!### 
OS: Ubuntu, MacOS and Windows

Old versions of commands:
- pull form aggregate without using -plla prefix
- pull from odk directory/sd card without -pc prefix
- export without -e or --export
Doesn't work on this branch. They result with running brriefcase.

@opendatakit-bot unlabel "needs testing"

File: src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java [hunk 1]
```diff
@@ -124,63 +124,75 @@ public static void main(String[] args) {
...
-      }
+      runLegacyCli(cmd, () -> MainBriefcaseWindow.showHelp(options));
+    }
+  }
 
-      if (cmd.hasOption(VERSION)) {
-        showVersion();
-        System.exit(1);
-      }
+  public static void runLegacyCli(CommandLine cmd, Runnable helpShower) {
```
Comment (yanokwa) [inline src/org/opendatakit/briefcase/ui/MainBriefcaseWindow.java]: I think referring to a launcher isn't clear. I'd prefer simpler language here.

> You are using old commands which will soon be removed from the CLI.
Please run Briefcase with --help to learn about the new commands.`

File: src/org/opendatakit/common/cli/CustomHelpFormatter.java [hunk 2]
```diff
@@ -53,7 +78,7 @@ private static void printRequiredParams(Map<String, String> helpLinesPerShortcod
   }
 
   private static void printOptionalParams(Map<String, String> helpLinesPerShortcode, Operation operation) {
-    System.out.println("  (optionally)");
+    System.out.println("Optional params for -" + operation.param.shortCode + " operation:");
```
Comment (yanokwa) [inline src/org/opendatakit/common/cli/CustomHelpFormatter.java]: I'd add a `System.out.println("\n")` before this.

**Comment by yanokwa** [comment]
I think this is ready to merge, but it seems wise to test this again. @ggalmazor does that sound reasonable? It might take two weeks and I want to make sure we don't cause conflicts.

File: src/org/opendatakit/common/cli/CustomHelpFormatter.java (hunk 2 above)
Comment (ggalmazor) [reply src/org/opendatakit/common/cli/CustomHelpFormatter.java]: I'd vote for not adding the blank line.

I tried it and went for keeping everything together because it felt more confusing as blank lines separate the different operations and their params.

**Comment by ggalmazor** [comment]
> I think this is ready to merge, but it seems wise to test this again. @ggalmazor does that sound reasonable? It might take two weeks and I want to make sure we don't cause conflicts.

Of course! This PR doesn't affect any other WIP.

**Comment by kkrawczyk123** [comment]
### Tested with success!

Verified on: Ubuntu, MacOs and Windows

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"
