### PR TITLE
Issue 608 Overwrite dialog displays behind Default export Conf instead of in front of on MacOS

### LINKED ISSUE #608: Overwrite dialog displays behind Default export Conf instead of in front of no MacOS
#### Software versions 
Briefcase v1.11.x, Java v1.8.x, operating system: MacOS

#### Problem description
Overwrite dialog displays behind Default export Conf instead of in front of on MacOS, screenshot attached:
screenshot from 2018-08-17 15-17-49

#### Steps to reproduce the problem
1. Run briefcase on MacOS
2. Open Export tab
3. Click on Set/Edit Default Configuration
4. Select Overwrite existing files checkbox

#### Expected behavior
Overwrite window should display in front of Default Export Conf window. 

#### Other information 
The issue is not visible on Ubuntu and Windows.

### PR DESCRIPTION
**Pull request by ggalmazor**
Closes #608 

This PR forces the overwrite confirmation dialog to appear using a dialog configured to be always on top as its parent component. This ensures that it stays on top of any other dialogs, even in a Mac computer.

#### What has been done to verify that this works as intended?
- Run in Linux and verified that it still works OK
- Run in Mac and verified that now it shows correctly on top

#### Why is this the best possible solution? Were any other approaches considered?
Although hacking Swing UI components is always a gamble, this change seems reasonably simple and safe.

#### Are there any risks to merging this code? If so, what are they?
None.

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
Nope.

### CODE REVIEW

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Ubuntu, MacOS and Windows.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

File: src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java [hunk 1]
```diff
@@ -339,7 +340,9 @@ private void triggerChangeExportMediaOverride() {
   }
 
   private boolean confirmOverwriteFiles() {
-    if (showConfirmDialog(this, "The default behavior is to append to existing files. Are you sure you want to overwrite existing files?", "", YES_NO_OPTION, PLAIN_MESSAGE) == YES_OPTION)
+    JDialog dialog = new JDialog();
+    dialog.setAlwaysOnTop(true);
+    if (showConfirmDialog(dialog, "The default behavior is to append to existing files. Are you sure you want to overwrite existing files?", "", YES_NO_OPTION, PLAIN_MESSAGE) == YES_OPTION)
```
Comment (dcbriccetti) [inline src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: The parent of the overwrite dialog should be the Export Configuration Dialog, not some new invisible one with magic keep-on-top powers. 😀

Comment (lognaturel) [reply src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: Hehe, good thing we were like “let’s wait until Dave looks at this before proceeding!” It always seems so obvious after you correct it...

Comment (dcbriccetti) [reply src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: It was a pretty good kludge! 😀

Comment (dcbriccetti) [reply src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: Sure, I’ll go along with that.

Comment (ggalmazor) [reply src/org/opendatakit/briefcase/ui/export/components/ConfigurationPanelForm.java]: Thanks, @dcbriccetti!

**Comment by ggalmazor** [comment]
Since there is no new commits after @kkrawczyk123's testing, I'm merging this one.
